sprout/basicproxy.cpp
sprout/ut/basicproxy_test.cpp

Mike,
Please can you review my fix to handle 6xx responses by cancelling outstanding requests?  This fixes #757.
I've UT-ed this, but one thing I wanted to check with you - the old code prioritized 487 responses over all other responses.  I can't see anything in RFC 3261 that says it should do.  Do you know why the old code did that?
Matt

[Reviewer: Mike] Handle 6xx responses by cancelling outstanding requests

---

sprout/stateful_proxy.cpp
sprout/ut/stateful_proxy_test.cpp

Fixes #842. The key change is https://github.com/Metaswitch/sprout/compare/upstream_routing?expand=1#diff-c70d752a0ba2b041697dce70b56ab72eR1480 (which forces Sprout to be the target for initial requests).
I've also had to rearrange some of the set_target logic - PJSIP doesn't like creating a transaction for tel: Request-URIs with no Route headers, so I had to make sure that the Route headers were added first.
UTed, about to live test (by retrying my failing tel: live test).

[Reviewer: Ellie] Make Bono always route to Sprout on initial access-proxy requests

---

include/regstore.h
sprout/notify_utils.cpp
sprout/regstore.cpp
sprout/ut/subscription_test.cpp

Hi Rob,
Please can you review my changes to escape characters correctly in our XML that we build for the NOTIFY reg-event package? This fixes https://github.com/Metaswitch/sprout/issues/749.
I've also changed the pub_gruu_pj_str method to be pub_gruu_str method since it only seemed to be return a pj_str for the purpose of building this xml, and I now want it in std::string form first. I hope this will become clear when you look at the code, and I hope this is sensible.
I think I'm escaping all the necessary fields, and no unnecessary fields. I've been using the following website to help - http://www.in2eps.com/fo-abnf/tk-fo-abnf-siprules.html.
Testing wise, all I've done is run the existing UTs. I had to fix up one UT that was expecting unescaped '<' and '>'. Otherwise, the xml_escape …

Reviewer RKD: [DO NOT MERGE] Escape necessary fields in reg-event XML

---

sprout/main.cpp
sprout/quiescing_manager.cpp

Fixes #853 .
There are three things I've done here:
* moved the creation of quiesce_unquiesce_thread down, so that we don't call pj_thread_register before the main thread calls pj_init
* called pj_bzero on the pj_thread_desc objects, to remove an uninitialised variable warning from valgrind
* added more debug logs around the QuiescingManager
I've tested live, by sending the QUIT signal to a Sprout (which reliably crashed before this change).

[Reviewer: Ellie] Fix segfault on quiescing

---

docs/Mangelwurzel.md
include/mangelwurzel/mangelwurzel.h
sprout/mangelwurzel/mangelwurzel.cpp
sprout/mangelwurzel/ut/mangelwurzel_test.cpp

Hi Matt,
Please can you review my change to mangelwurzel so that it doesn't mangle the Request URI on in-dialog requests? As discussed, mangling the Request URI on in-dialog requests because we've mangled it on the initial request doesn't make sense. We may wish to mangle it for other reasons on in-dialog requests, but right now we don't have a well defined use case for this.
I've tested by running the UTs and deploying on a system.
I've updated the design.
Thanks,
Graeme

Reviewer MIRW: Mangelwurzel leaves the Req URI alone on in dialog requests

---

sprout/bgcfsproutlet.cpp
sprout/ut/scscf_test.cpp
sprout/ut/test_stateful_proxy_enum.json

Hi Andy,
Can you review this? It fixes https://github.com/Metaswitch/sprout/issues/951. The fix is as described in the issue.
The new UT crashes without the fix, and doesn't crash with the fix.
I did a code read of all the other places we called free_msg and they look fine.
Grab me if you've got any other questions.
Thanks!
Graeme

Reviewer AMC: Don't crash in BGCF when ENUM returns invalid rule

---

include/regstore.h
sprout/handlers.cpp
sprout/registrar.cpp
sprout/registration_utils.cpp
sprout/regstore.cpp
sprout/subscription.cpp
sprout/ut/handlers_test.cpp
sprout/ut/mock_reg_store.h
sprout/ut/registrar_test.cpp
sprout/ut/subscription_test.cpp

Ellie, please could you review my fix for #977.
This changes `RegStore::set_aor_data` to return a `Store::Status` rather than simply success/failure. I have also updated the users of the store to fail the request in progress if the store returns `Store::ERROR` (the exception is the registration timeout handler which continues to return 200 OK to chronos). 
Existing UTs all run fine, and I have added new UTs to cover failures of the RegStore. I will also check the live tests run OK, but I'm having trouble setting up a working deployment at the moment.

[Reviewer: Ellie] Make the RegStore distinguish between data contention and genuine errors. 

---

sprout/subscription.cpp
sprout/ut/subscription_test.cpp

This fixes a regression in https://github.com/Metaswitch/sprout/pull/979 where CSeqs were not updated after processing a SUBSCRIBE. The fix is to move the CSeq increment to before we write the AoR back to the store. 
Tested with a new UT.

[Reviewer: Ellie] Fix non-incrementing CSeqs

---

sprout/enumservice.cpp
sprout/ut/enumservice_test.cpp

Fixes https://github.com/Metaswitch/sprout/issues/950. Exising UTs pass, and I've added a specific UT to confirm that Perl regexes aren't used.

[Reviewer: Matt] POSIX regexes for ENUM

---

sprout/mementoasplugin.cpp

Hi Rob. This is another co-req change needed under sto1773 (I forgot that the Memento sproutlet is built as part of sprout and not memento). Note that I haven't removed any error checking here - start never returns an error when the store is configured with no threads (as the call list store is). 
Tested by checking the memento live tests pass.

[Reviewer: Rob] Make memento AS plugin cope with updated cassandra store

---

sprout/main.cpp

[Reviewer: Andy] Ensure process name passed to openlog() lasts for duration of program

---

sprout-base.root/usr/share/clearwater/bin/poll_sprout_http.sh

Matt, can you review this change to check that the S-CSCF is enabled when running poll_sprout_http. 
Fixes #999 
Tested live

[Reviewer: Matt] Check for S-CSCF

---

debian/restund.prerm

A really boring PR to not delete the restund user when upgrading restund. This prevents an error message when upgrading. This follows the pattern we use for the bono/sprout users.
Tested by upgrading restund and checking that no error message was produced. Restund was running happily after the upgrade.

Reviewer: Rob] Don't remove restund user when upgrading

---

sprout/acr.cpp
sprout/ut/acr_scscfpublish.json
sprout/ut/acr_test.cpp

Ellie,
Please can you review this fix to encode Message-Body correctly?  It's encoded as an array of strings when it should be an array of objects containing strings.  Reviewing with `?w=1` might be clearer.
Live-tested only as there's no UT for ACRs.
Matt

[Reviewer: Ellie] Encode Message-Body correctly

---

include/bgcfservice.h
include/pjutils.h
sprout/bgcfservice.cpp
sprout/pjutils.cpp
sprout/sprout_test.mk
sprout/ut/pjutils_test.cpp

Fixes https://github.com/Metaswitch/sprout/issues/964. I think this accepts all valid instances of `global_number_digits` from http://www.in2eps.com/fo-abnf/tk-fo-abnf-sipuri.html#teluri - I haven't worried about the additional complexity of local_number_digits, because we use this function to decide:
* whether to do an ENUM lookup
* whether to convert a SIP URI to a TEL URI in the I-CSCF
and both operations are only valid for global E.164 numbers (even if we have `enforce_user_phone=N`, it just doesn't make sense to do a ENUM or LIR lookup for `tel:*1234A#`).

[Reviewer: Ellie] Ignore separators in is_user_numeric

---

include/acr.h
include/sproutsasevent.h
sprout/acr.cpp
sprout/stateful_proxy.cpp

Andy,
Please can you review this fix to #1006?  It's basically as we discussed - a new `ACR::set_default_ccf` method.
I've also changed `ACR::send_message` to report an error if there are no CCFs or ECFs - it's an interface violation to send like this.
I've also downgraded a couple of spammy error logs to infos.
All live-tested, and UTs run cleanly.
Matt

[Reviewer: Andy] Default CCF on ACRs from Bono

---

sprout/ut/coverage-not-yet

My new UTs for the load monitor are a bit more complex than I thought (requiring a second round of cpp-common changes), so I'm excluding the load monitor from coverage to allow you to cut the release.

[Reviewer: Ellie] Temporarily exclude load monitor from coverage checks

---

debian/bono.init.d
include/cfgoptions.h
include/sipresolver.h
sprout-base.root/etc/init.d/sprout
sprout/main.cpp
sprout/pjutils.cpp
sprout/sipresolver.cpp

Andy,
Please can you review this fix to make the DNS blacklist duration configurable? There's no UT for this, but I've tested it live (and it's actually just refactoring).
This is the fix for sprout.  Once you've reviewed, I'll apply the same fix to homestead, ralf, memento, etc.
Matt

[Reviewer: Andy] Make DNS blacklist duration configurable

---

clearwater-sip-stress.root/usr/share/clearwater/bin/sip-stress

Rob,
Please can you review this fix to sprout to use a dumb terminal with clearwater-sip-stress.  On Juju, the terminal isn't always set correctly, which can break this function.
Matt

[Reviewer: Rob] Tell sipp to use a dumb terminal

---

debian/sprout-base.postinst
sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_chronos_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_memcached_plugin.py
sprout-base.root/usr/share/clearwater/cluster-manager/plugins/sprout_memcached_plugin.py

Can you review `sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_memcached_plugin.py`?
Note that:
* I'll rename `write_cluster_settings` to `write_memcached_cluster_settings`
* I've gone for fairly minimal logs, because the logs generated before calling into the plugin and the logs generated by run_command should be enough to tell what's going on

[Reviewer: Ellie] Memcached clustering plugin

---

include/avstore.h
sprout/authentication.cpp
sprout/avstore.cpp

Andy,
Please can you review this fix to make Sprout retry AV tombstones writes that fail due to CAS.  We don't normally expect them to fail due to genuine CAS, but they can fail if we read from a backup and then try to write back to a (previously-unavailable) primary.  This fixes #1010.
There's no UT infrastructure for failing memcached writes, but I have tested live.  I ran up a system with 2 Sprouts and ran light (10kBHCA) stress through it.  Without the patch, shortly after I killed Memcached, I saw logs of the following form:
```
02-05-2015 00:58:22.963 UTC Error avstore.cpp:78: Failed to write Authentication Vector for private_id 2010000421@mirw.cw-ngv.com
02-05-2015 00:58:22.963 UTC Error authentication.cpp:619: Tried to tombstone AV for 2010000421@mirw.cw-ngv.com/0f3ea1dc23b199f5 …
```

[Reviewer: Andy] Retry AV tombstones writes that fail due to CAS

---

include/authentication.h
sprout/authentication.cpp
sprout/sprout_base.mk

We've removed all references to pjmedia from sprout_base, but some app servers require it. So we need to explicitly link it. Unfortunately, pulling this in also pulls in a reference to a symbol called mod_auth, so we rename our mod_auth. mmtel and call_diversion_as now load agian.

Reviewer AMC: Pull in pjmedia, requires rename of mod_auth

---

sprout-base.root/etc/init.d/sprout

Calls bracket_ipv6_address when creating the scscf_uri. 
Fixes #1028  (but not the wider issue covered by #1029 )

[Reviewer: Rob] Add in bracket call

---

sprout-base.root/etc/init.d/sprout

Tested live, with a version of poll-sip that uses $public_hostname in the request URI. OPTIONS polls without this change fail with 483 Too Many Hops, and succeed with this change.
(I've verified that having a trailing `,` when alias_list is undefined is harmless.)

[Reviewer: Ellie] Use public addresses as aliases

---

sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_chronos_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_memcached_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_remote_memcached_plugin.py

As discussed, only Sprout nodes which are S-CSCFs should join the Memcached or Chronos clusters. This implements that, by making the plugins run a Bash command that checks if $scscf has been explicitly set to 0.
This is pretty unpleasant code, and our S-CSCF/I-CSCF config model is hacky in other ways (e.g. it breaks shared config) - can you raise an issue (or ask for a user story) to track fixing this up?
I haven't tested, but I'll spin up a Sprout node and:
* not mention scscf in the config file and verify that these plugins load
* explicitly set scscf=5054 in the config file and verify that these plugins load
* explicitly set scscf=0 in the config file and verify that these plugins don't load

[Reviewer: Ellie] Disable plugin loading for I-CSCF

---

sprout-base.root/usr/share/clearwater/clearwater-config-manager/plugins/sprout_bgcf_json_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-config-manager/plugins/sprout_enum_json_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-config-manager/plugins/sprout_json_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-config-manager/plugins/sprout_scscf_json_plugin.py

I picked up the latest code out of master and it didn't work. It looks like plugin_utils.py has been moved into etcd_shared, but the references here and in clearwater-etcd haven't been updated.

[Reviewer: Andy] Fix path to plugin_utils

---

sprout/main.cpp

This PR moves the various HTTP handlers we use into the same scope as the `sem_wait` that main spends most of it's time in (so that the memory the handlers use won't be reused). 
This manifested as an HTTP flow from chronos to sprout appearing in the SAS call flow. I have confirmed that this change fixes that issue.

[Reviewer: Andy] Make sure the HTTP stack handlers are always using valid memory. 

---

README.md
docs/Bono Sprout Architecture.md
docs/CallDiversionAS.md
docs/IscInterface.md

I spotted the two spelling errors, and the clearwater-docs wiki just points you to the ReadTheDocs site. I made my best guess at the corresponding new pages.

Fix two spelling errors and links to documentation

---

sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_chronos_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_memcached_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_remote_memcached_plugin.py

The cluster-manager logs contain the following in the mainline case:
```
27-05-2015 17:55:34.406 UTC ERROR plugin_utils.py:58: Command . /etc/clearwater/config; [ "x$scscf" = "x0" ] failed with return code 1 and printed output ''
```
This PR changes how we check the SCSCF value to avoid the misleading error log. Tested live

[Reviewer: Andy] Change how S-CSCF value is checked to avoid error logs

---

include/cfgoptions.h
include/stack.h
sprout-base.root/etc/init.d/sprout
sprout/main.cpp
sprout/stack.cpp

Steve,
Please can you review the second half of my fix to the TCP connection timeout aspect of #1018?
This simply plumbs the connection timeout through to PJSIP.
Note that even after this fix there are still issues surrounding AS timeouts.  In particular,
*   if you don't specify TCP transport on the AS URI, sprout falls back to UDP after the TCP connection attempt times out, and so doesn't try other TCP targets - obviously, the work-around to this is simply to specify TCP transport
*   this fix handles the case where an AS takes too long to connect, but it doesn't handle the case where an AS accepts the connection but doesn't respond to the SIP request - maybe that's OK, though, or at least much less mainline (I think we're getting into undefined parts of the specs here).
Cheers,
Matt

[Reviewer: Steve] Make SIP TCP connect timeout configurable

---

include/sprout_pd_definitions.h
sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_chronos_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_memcached_plugin.py
sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_remote_memcached_plugin.py
sprout/bgcfservice.cpp
sprout/enumservice.cpp
sprout/scscfselector.cpp

Tested live:
```
Jun  4 13:12:50 ip-10-181-26-75 sprout[704]: 2041 - Description: The ENUM file is invalid. @@Cause: Sprout is configured to use file-based ENUM, but the configuration file does not exist. @@Effect: Sprout will not be able to translate telephone numbers into routable URIs. @@Action: Confirm that /etc/clearwater/enum.json is the correct file to be using. If not, correct /etc/clearwater/shared_config. If so, check that it is a valid and correctly formatted file.
Jun  4 13:12:50 ip-10-181-26-75 sprout[704]: 2047 - Description: The file listing BGCF routes is not present or empty. @@Cause: The /etc/clearwater/bgcf.json file, defining which BGCF routes to use, is not valid (due to invalid JSON or missing elements). @@Effect: Sprout will not be able to route some or all calls …
```

[Reviewer: Alex] Extra ENT logs in support of clearwater-config-manager

---

debian/bono.init.d
include/cfgoptions.h
include/stack.h
sprout-base.root/etc/init.d/sprout
sprout/main.cpp
sprout/stack.cpp

Alex,
Please can you review this enhancement to add a `sip_tcp_send_timeout` option that controls the amount of time we'll wait for acknowledgement of a TCP PSH.
I've not UT-ed, because there isn't anything to UT, but I have tested live (from Bono to Sprout) and saw a transaction fail quickly with a transport failure if Sprout drops off the network.
Matt

[Reviewer: Alex] Add configurable SIP send timeout

---

include/icscfsproutlet.h
sprout/icscfsproutlet.cpp
sprout/ut/icscfsproutlet_test.cpp

A fix to a technical spec misalignment. TS 24.229 5.3.2.1 says that "user=phone" => Tel URI conversion in I-CSCF on Initial Requests should only be done for global numbers ("...with the user part starting with a + ...") if the enforce_global_lookups feature is turned on.
Tested with a UT that verifies that an INVITE for a "user=phone" SIP URI with a non global number does not match a location record for the corresponding Tel URI and is rejected, and another that verifies that rejection doesn't happen if enforce_global_lookups is off

Review AMC:  Only translate user=phone SIP URIs to tel URIs in ICSCF if number is global (or enforce_global_lookups not set)

---

sprout/pjutils.cpp
sprout/registration_utils.cpp
sprout/sprout_test.supp
sprout/ut/registrar_test.cpp

Andy, can you review this change to check whether the tdata is pending before using it in a retry. This uses the same logic as #925. 
I've also removed some leak suppressions that aren't needed anymore
Fixes #1069

[Reviewer: Andy] Iss1069

---

debian/sprout-base.postinst

Checks whether cluster/config manager is installed before stopping them. If you're happy with this, I'll make the same fix to Memento/Ralf/Homer/Homestead
Part of the fix for #1084

[Reviewer: Andy] Check for install

---

debian/clearwater-sip-stress.init.d

***Not to be merged whilst the code is frozen***
Hi Rob,
Can you have a look at my proposed change to restart clearwater-infrastructure before starting SIPp? Any reason why this isn't a good idea? Saves having to remember to do it manually, and there doesn't seem to be much reason not to just do it automatically.
Tested by adding the line to an existing clearwater-sip-stress node and starting clearwater-sip-stress.
I can't find any associated doc changes so that's good...
Thanks,
Graeme

[Reviewer: RKD] Restart clearwater-infrastructure before starting SIPp

---

sprout/basicproxy.cpp
sprout/ut/basicproxy_test.cpp

Andy,
Please can you review this partial fix to issue #1095?  It simply disables retry on transaction-level timeouts - they're too slow to be any use and cause extra work (and possible race conditions/crashes) when they're hit.
Thanks,
Matt

[Reviewer: Andy] Don't retry SIP transactions on SIP-level timeout - it's too slow

---

include/scscfsproutlet.h
sprout/scscfsproutlet.cpp

Matt, this makes the `AsChain` (which is reference-counted) be the owner of the `ACR` for a single S-CSCF phase (`orig`, `orig-cdiv` or `term`).  We discussed the change (and @mike-evans also proposed a similar approach).  I've tested through the existing UTs which ensure that we're not leaking any ACRs and that we're producing ACRs in the correct places, I've not tested live.
One thing that's a bit of a shame is I can't see a way to stop someone just reading `_acr` when they should be calling `get_acr()` to check the `_as_chain` first, any ideas?

Reviewer Matt - Store the ACR in the AsChain

---

sprout/icscfsproutlet.cpp
sprout/ut/icscfsproutlet_test.cpp

This is a less-wide-ranging (and therefore safer) fix for issue #1091.
I haven't defined a ICSCFSproutletDropItTsx - this seemed like overkill, so I've just dropped it in the existing ICSCFSproutletTsx.
UTed but not tested live.

[Reviewer: Matt] Drop rogue ACKs within the I-CSCF

---

mk/platform.mk

This is the same Makefile change that I made to cedar that you reviewed earlier this week.  Basically, we build the `.d` file alongside the `.o` file rather than up-front.
Tested by running make various times, touching random files between some runs.  If you're happy with this, I'll apply the same change to other users of `platform.mk`.

Reviewer Matt - Don't have specific rules for .depends files

---

include/pjutils.h
sprout/handlers.cpp
sprout/pjutils.cpp

Rob, please could you review this PR that fixes #924. Although we are logging some new markers, the perf impact should be negligible (as they are still much smaller than the SIP message itself).
Tested live, by checking a call could be found by searching on both the calling and called URIs.

[Reviewer: Rob] Log the to/from URI as SIP URI markers

---

include/pjutils.h
sprout/handlers.cpp
sprout/pjutils.cpp

This updates #1136 so that Clearwater is consistent with other the way other products log URIs and DNs on calls, registrations and subscriptions. Please can you review.
I have tested by doing the following. In each case I checked that the trace could be found by URI and DN (if appropriate) and that the results look sensible in SAS. 
* Register with a DN-like URI.
* Register with a non-DN-like URI.
* Call a DN-like URI
* Call a non-DN-like URI.
I will run through these tests on the staging system as well once the PR is merged.

[Reviewer: Rob] Be consistent with other devices when logging SIP URIs and DNs

---

debian/bono.init.d
sprout-base.root/etc/init.d/sprout

I saw some of the errors from https://github.com/Metaswitch/sprout/issues/1128 in the Sprout log. This stops them.

[Reviewer: Ellie] Don't try and load MIBs on Sprout/Bono startup to avoid log spam

---

sprout/authentication.cpp
sprout/basicproxy.cpp
sprout/bono.cpp
sprout/common_sip_processing.cpp
sprout/pjutils.cpp
sprout/registrar.cpp
sprout/subscription.cpp

Fixes https://github.com/Metaswitch/sprout/issues/923 and https://github.com/Metaswitch/sprout/issues/575.
For testing, I'm planning to register and make a call through Perimeta, Sprout and CFS TAS and verify that the whole thing gets correlated in SAS, and also check that the number of messages we send to SAS hasn't increased overall for that call flow. Sound sensible?

[Reviewer: Andy] Do all SAS Call-Id/Via branch logging in one place

---

include/sproutlet.h
include/sproutletappserver.h
include/sproutletproxy.h
sprout/sproutletappserver.cpp
sprout/sproutletproxy.cpp

This allows creation of blank REQUESTs to be used by sproutlets when making downstream requests, when re-using existing requests is not appropriate.
The caller is responsible for filling in all the mandatory SIP headers before sending the message.

Add create_request method

---

sprout/sproutletproxy.cpp
sprout/ut/mocktsxhelper.h
sprout/ut/sproutletproxy_test.cpp

Fixes the test build break because of a missing implementation of the new method.

Add mock for create_request

---

sprout-base.root/etc/init.d/sprout

Passes the max_session_expires value from /etc/clearwater/config to Sprout. Tested live. 
Fixes #1180

[Reviewer: Andy] Pull in max_session_expires

---

sprout/registration_utils.cpp

I hit a crash in UT caused by the registration_utils.cpp::third_party_reg_stats_tables pointer being NULL. This can happen if you call `remove_bindings` before `(de)register_with_application_servers`. I have fixed this by making `registration_utils.cpp` more defensive and checking its pointer. 
I think there is still a more minor issue where 3rd party reg stats will be wrong if we call `remove_bindings` first. I will raise an issue for this (it's really low urgency). 
Tested in UT.

[Reviewer: Rob] Make handling of 3rd party registration stats more defensive

---

sprout/icscfplugin.cpp
sprout/scscfplugin.cpp
sprout/ut/scscf_test.cpp

Fixes #1029. With this change, and the following config:
```
$ cat /etc/clearwater/local_config
local_ip=fd5f:5d21:845:1402:407e:aa42:6989:4d58
public_ip=fd5f:5d21:845:1402:407e:aa42:6989:4d58
public_hostname=sprout-1
etcd_cluster="fd5f:5d21:845:1402:407e:aa42:6989:4d58"
```
Sprout loads without error logs and the S-CSCF sproutlet handles requests I send it (using SIPp). I don't have a full IPv6 test rig, so haven't made an end-to-end call.

[Reviewer: Ellie] Bracket the IPv6 address before using it (ready to merge)

---

include/sproutletproxy.h
sprout/sproutletproxy.cpp

Andy,
Please can you review this (which fixes #1124)?  See the issue for details of the problem, but the fix is to count the number of times we've re-entered SproutletWrapper::process_actions and not delete the SproutletWrapper if so.
I've run the UTs, but not enhanced them because they don't have support for failing transports (and it looks quite fiddly to add).  I've also run long stress runs, both at full load and at light load under valgrind, and neither seen the crash nor seen the signature from valgrind.
Thanks,
Matt

[Reviewer: Andy] Count re-entrancy in SproutletWrapper::process_actions

---

include/scscfsproutlet.h
sprout/scscfsproutlet.cpp

Speculative fix to https://github.com/Metaswitch/sprout/issues/1202.
It compiles, but I haven't live-tested - I've reproed https://github.com/Metaswitch/sprout/issues/1202 on the VMware rig, though, so I can live test once it goes into the 'latest' repo.

[Reviewer: Alex] When creating a new AS chain after a retarget, reuse the SAS trail ID

---

sprout/bgcfservice.cpp
sprout/ut/bgcfservice_test.cpp
sprout/ut/test_bgcf_misspelt_route.json

Check for "route" in the BGCF rule before dereferencing it.  UT in pull request.  I've also removed the old "Check the log string" tests as they were lame.

Reviewer Alex - Detect missing 'route' in BGCF JSON file

---

include/acr.h
include/scscfsproutlet.h
sprout/acr.cpp
sprout/aschain.cpp
sprout/authentication.cpp
sprout/bgcfsproutlet.cpp
sprout/bono.cpp
sprout/icscfrouter.cpp
sprout/icscfsproutlet.cpp
sprout/registrar.cpp
sprout/scscfsproutlet.cpp
sprout/subscription.cpp
sprout/ut/acr_test.cpp
sprout/ut/scscf_test.cpp

As per the discussion in #1199, this change limits the S-CSCF to perform billing at the beginning of originating and at the end of terminating, removing the billing performed on `cdiv` and removing the spurious INTERIM billing if your `Record-Route` settings cause multiple hops per call leg.
Fixes #1199.
I've tested the `billing-role` change and the `ACR::cancel()` function in UT.  I'll confirm the extra START ACR with a SAS trace on a live system once this is merged.

Reviewer Alex - Remove CDIV-triggered ACRs

---

sprout/authentication.cpp
sprout/ut/authentication_test.cpp

Rob, please could you review this change to strip any Proxy-Authorization headers out of the message before passing the request up out of the auth module. 
I've not done this for Authorization headers as 3rd party REGISTERs may need to include the entire received REGISTER request :-0.
Tested in UT. Fixes #1213.

Reviewer: Rob] Strip Proxy-Authorization headers

---

sprout/authentication.cpp

Very simple trail ID plumbing fix. I tested this by writing a script to lint our SAS protocol flows. I ran the live tests before the fix and checked the lint found the problem, and after the fix to prove the problem was fixed.

[Reviewer: AMC] Pass the SAS trail ID into the chronos connection when setting auth timers

---

debian/bono.init.d

I noticed that no Bono nodes have been logging for a while - this is because short arguments like `-a` are incompatible with using `=` for arguments. This switches all the short-form arguments to long-form ones.

[Reviewer: Ellie] Reinstate Bono logging

---

include/acr.h
sprout/acr.cpp
sprout/scscfsproutlet.cpp
sprout/ut/acr_scscftermcall_start_changed_call_id.json
sprout/ut/acr_test.cpp

Andy, please can you review this PR that fixes #1222. As discussed, I've added a new method to allow the S-CSCF to override the default session ID for an ACR, and made the S-CSCF sproutlet call this whenever it record-routes itself into a dialog to do billing. 
I tested the ACR code in UT. I tested the entire change (including the S-CSCF part) live, by using mangelwurzel to change the call ID and checking in SAS that the correct session IDs were used on INTERIMs and STOPs send by sprout.

[Reviewer: Andy] Make the S-CSCF override the session ID when deciding to record-route

---

sprout/bgcfsproutlet.cpp

Speculative fix for issue #1224. UTs still pass.

[No review required] Initialize BGCF _acr pointer to NULL

---

sprout/main.cpp

f58cbc8a0 put the HttpStack initialisation in completely the wrong
place.

Fix mismerge

---

sprout/basicproxy.cpp
sprout/bono.cpp
sprout/pjutils.cpp
sprout/sproutletproxy.cpp
sprout/ut/scscf_test.cpp

This pull request fixes #873 by correcting the Reason field in the History-Info header. The old behavior was to include each part of the Reason field as a separate parameter in the URI. The fixed behavior is to URL escape the values into a single parameter as per RFC 7044.
I've checked the RFC and confirmed that I agree with the interpretation in the issue. I've run the live tests against my code with no errors.

Correct Reason parameter in History-Info header

---

include/bgcfservice.h
include/enumservice.h
include/scscfselector.h
sprout/bgcfservice.cpp
sprout/enumservice.cpp
sprout/scscfselector.cpp

Andy
Would you mind reviewing these changes to allow Sprout to pickup changes to enum.json.
A couple of areas I'm less confident on are:
* The locking using pthread mutexes.
* Memory management - Looking at [scscfselector](https://github.com/Metaswitch/sprout/blob/dev/sprout/scscfselector.cpp) line 151, we don't seem to destroy the old list (_scscfs) in the way I have done in my change. I think this might mean that scscfselector leaks the memory storing the config whenever it is reloaded, although if I'm misunderstanding something then my changes may be wrong instead.
Fixes #1209 
I tested this on our system with both good and broken enum.json files and it behaved as expected.
Thanks,
Tom

[Reviewer: Andy] Fixes #1209 - Reload enum json on sighup

---

sprout/regstore.cpp
sprout/ut/regstore_test.cpp

Fix to copy the _uri as well when copying an AoR
Tested in UTs

[Reviewer: Rob] Copy URI setting as well

---

sprout/bono.cpp
sprout/sproutletproxy.cpp

As discussed, please can you review this PR to send a flush marker on trails that are handled statelessly (ACKs, and requests rejected by bono). I tested this by running the live tests and checking that they worked, and that my SAS lint reported no unflushed trails related to ACK processing.

[Reviewer: AMC] Flush trails on requests that are handled statelessly

---

sprout/ut/siptest.cpp

Required to achieve 100% code coverage in the sproutlet proxy.

[No review required] Set a trail ID when injecting SIP messages in UT

---

include/cfgoptions.h
sprout-base.root/etc/init.d/sprout
sprout/main.cpp
sprout/memento_as.mk
sprout/mementoasplugin.cpp

Implements configuration of https://github.com/Metaswitch/memento/pull/105
The URL to notify is configured in the `memento_notify_url` setting in shared config.

Pass memento notify URL to memento

---

sprout/ut/mock_sproutlet.h
sprout/ut/mock_sproutletproxy.h
sprout/ut/sproutletproxy_test.cpp

On the other hand I have a pull request that will make its way across to you in due course to re-introduce these mocks in cpp_common, where they can be used by sproutlet unit tests too.

Move MockSproutletProxy etc to make them generally available

---

sprout-base.root/etc/init.d/sprout

In https://github.com/Metaswitch/cpp-common/pull/397, we discussed that our initial token rate was probably too low.
I've now taken measurements suggesting 250 req/sec/core is sensible (and an underestimate, if anything) - see https://github.com/Metaswitch/sprout/issues/1251#issuecomment-157803199. This sets it to that.

[Reviewer: Alex] Default the initial token rate to 250 * num cores

---

sprout-base.root/etc/init.d/sprout

Alex,
Please can you review this fix to https://github.com/Metaswitch/sprout/commit/b3eb91d98e6cb517b83478fcdec1e9eeff0a24ad (which you reviewed yesterday)?
Basically, by moving dotting in `/etc/clearwater/config` down, we had no longer set up `local_ip` before we tried to use it - this meant that our `/etc/clearwater/cluster_settings` file was broken if we were running without `clearwater-cluster-manager` (which would otherwise set up this file).
Not yet live-tested - will do so on Docker once the build completes.
Matt

[Reviewer: Alex] Fix running without clearwater-cluster-manager

---

src/authentication.cpp
src/ut/authentication_test.cpp

A Sprout node got a re-REGISTER with the following Authorization header:
`Authorization: Digest username="6510803201@great-lakes2.datcon.co.uk",realm="great-lakes2.datcon.co.uk",nonce="1ecf59a675a7162d",uri="sip:great-lakes2.datcon.co.uk",response="5e279ba845e1a866d8fc87080165091d",cnonce="44448888",opaque="222481f80f449504",qop=auth,nc=00000002`
This crashed Sprout, because:
- there was a response, so we tried to challenge it
- there was an expired nonce, so we got NULL as our AV
- there was no explicit algorithm, so we tried to call `av->HasMember("digest")`
This fixes that up (defaulting to Digest in that case). I confirmed my UT reproduces the crash.

[Reviewer: Andy] Fix authentication crash

---

mk/sprout.mk

This is a holding pattern fix (while I determine what we do with the code in `tests`).  Prevents errors when running `make clean` at the top level of Sprout's codebase.

Reviewer Matt - Don't clean FV tests when doing top-level clean

---

include/analyticslogger.h
include/connection_pool.h
src/Makefile
src/connection_pool.cpp

So that eg we can build under clang.
Also make fixes so that a clang build actually succeeds:
- unused private variables
- sleep(0.1) is truncated to sleep(0), which is pointless anyway

Respect standard build environment variables

---

src/ut/sproutletproxy_test.cpp

Discussed with @mbt-msw , who wrote this test - he agrees that the intention is to only set a timer on the first response received, so I've changed the type of `_response` to int.
UTs pass, and this is test code only.

[No reviewer] Fix a compiler warning about incrementing a bool

---

src/sproutletproxy.cpp

This fixes a SUBSCRIBE routing issue whereby, if I-CSCF identifies the target S-CSCF for a SUBSCRIBE as the local Sprout, it routes the request to the S-CSCF Sproutlet, thereby bypassing the subscription module and causing the SUBSCRIBE to be routed (erroneously) to the subscribee instead of being processed on the local Sprout
This fix stops the I-CSCF from attempting to use sproutlets, instead sending it to the local S-CSCF the long way round (so that it is sent to the subscription module correctly by PJSIP).
Tested live using a P-CSCF configuration that sent re-event SUBSCRIBEs to the I-CSCF and sending in reg-event subscribes for local subscribers.

[Reviewer AMC] If a route header is present, only route to a sproutlet if this is NOT a SUBSCRIBE

---

src/sproutletproxy.cpp

Reverts Metaswitch/sprout#1286

Revert "[Reviewer AMC] If a route header is present, only route to a sproutlet if this is NOT a SUBSCRIBE"

---

src/subscriber_data_manager.cpp
src/ut/registrar_test.cpp

This fixes the two issues reported in #1274:
* Use the actual AoR instead of the literal string 'aor'
* When binding A expires, don't send a NOTIFY to binding A announcing the subscription is terminated - that's pointless
I think the UTs cover all the right behaviour here - I don't think there's much value in testing live.

[Reviewer: Ellie] Fix subscriptions for expired users

---

src/Makefile
src/authentication.cpp
src/hssconnection.cpp
src/ut/authentication_test.cpp

Fixes #1299  - Where we were rejecting resync responses instead of passing them through to the HSS.
Tested live.
Andy - Please could you review along with related Homestead PR.
Cheers,
Tom

[Reviewer Andy] Add aka resync to sprout

---

src/scscfsproutlet.cpp
src/ut/scscf_test.cpp

Fixes iss1267 
https://github.com/Metaswitch/sprout/issues/1267
Instead of only adding a tel URI alias if it matches the user of the SIP URI, we now check if there is a tel URI alias whose username matches the SIP URI. If there is we add it to the P-Asserted-Identity header and if there isn't we add the first tel URI in the alias list.

[Reviewer: Rob] Fixes iss1267: Adds a tel URI alias to the P-Asserted-Identity header

---

src/ut/logger_test.cpp

Uses cw_control_fopen to allow fopen failures to be simulated.
Adds test which uses this to force a logger to re-open its log file.

[Reviewer AJH] Add unit test to cover failure to open log files.

---

bono.root/usr/share/clearwater/infrastructure/scripts/restart/bono_restart

Use stop rather than quiesce to restart Bono (as this is bugged - https://github.com/Metaswitch/sprout/issues/1296)

[Reviewer: Graeme] Update bono_restart

---

include/handlers.h
include/subscriber_data_manager.h
src/handlers.cpp
src/main.cpp
src/registrar.cpp
src/scscfsproutlet.cpp
src/subscriber_data_manager.cpp
src/ut/chronosconnection_test.cpp
src/ut/fakechronosconnection.cpp
src/ut/fakechronosconnection.hpp
src/ut/handlers_test.cpp
src/ut/scscf_test.cpp
src/ut/subscriber_data_manager_test.cpp

This is the bulk of the work. 
I've added the AoR class methods for getting the number of bindings and subscriptions, and the next expiry time, as we decided. 
The SubscriberDataManager, and SubscriberDataManagerTests are where the biggest changes are. 
I'd particularly appreciate a look at the send_timers logic, and the tests associated with sending timers that i've added, to make sure i'm not missing some areas of testing.
There's also a number of minor changes throughout:
- changed RegSubTimeoutTask to AoRTimeoutTask
- made modifications to support the map of tags throughout.
- cleared out a couple of bits of whitespace i saw Andrew introduced in scscf-sproutlet code.
Let me know if anything isn't clear. Feedback as soon as is plausible would be good so i can try to get it in this week …

[Reviewer: Chris] Stats api update

---

src/handlers.cpp

This is a trivial change for #1201.
I think this is actually so trivial that I'm not proposing to test it before merging - I'll merge, then register a client on the VMware system and make it fail (i.e. kill my X-Lite process), and make sure I get a sensible SAS log.

[Reviewer: Alex] Pass trail ID on deregistration

---

src/ut/siptest.cpp

This takes a slightly scattergun approach of controlling time in all our SIP unit tests, to fix #1324. I can't think of any other tests where this would be useful (it seems that the main offender is SIP registration expiry times, which only Sprout handles, I think), and I can't think of any tests where this is the wrong thing to do (if a test is reliant on time moving forwards, it should do so explicitly with cwtest_advance_time).
I've:
* verified that `make test` still works
* added a `sleep(5)` at the start of `SubscriberDataManager::set_aor_data` to emulate a test taking longer than expected, which makes the test fail (due to an "expires=295") without this change, and pass with this change

[Reviewer: Adam] Control time in unit tests

---

sprout-base.root/usr/share/clearwater/infrastructure/scripts/sprout.monit

See clearwater-infrastructure for the new script which this uses.

[Reviewer Adam] Update sprout to use new uptime infrastructure.

---

src/pluginloader.cpp

This removes the check on file type for plugins, replacing it with a check for a ".so" extension (just to filter out "." and "..", which otherwise gave spurious error logs).
I've tested by creating a directory, block device and symlink in the pluginsdirectory - dlopen follows the symlink and fails gracefully on the other two.
Fixes #1340 .
```
$ ls -l /usr/share/clearwater/sprout/plugins/
total 588
brw-r--r-- 1 root root  7, 21 Mar  1 14:16 blkdev.so
drwxr-xr-x 2 root root   4096 Mar  1 14:15 directory.so
-rw-r--r-- 1 root root 208288 Mar  1 14:37 sprout_bgcf.so
-rw-r--r-- 1 root root 249536 Mar  1 14:37 sprout_icscf.so
lrwxrwxrwx 1 root root     24 Mar  1 14:43 sprout_mmtel_as.so -> /root/sprout_mmtel_as.so
-rw-r--r-- 1 root root 138744 Mar  1 14:37 sprout_scscf.so
```
```
01-03-2016 …
```

[Reviewer: Matt] Allow plugins to load on filesystems which don't support readdir

---

include/acr.h
include/pjutils.h
include/scscfsproutlet.h
src/acr.cpp
src/authentication.cpp
src/bgcfplugin.cpp
src/bgcfsproutlet.cpp
src/bono.cpp
src/icscfplugin.cpp
src/icscfsproutlet.cpp
src/main.cpp
src/pjutils.cpp
src/registrar.cpp
src/scscfsproutlet.cpp
src/subscription.cpp
src/ut/acr_test.cpp

Andy, please can you review this PR to make sure the registrar sends ACRs even when it rejects REGISTERs. This contains a big refactor to move some enums into the `ACR` class to avoid them polluting the namespace (I started to hit this because I included `acr.h` in `pjutils.h` and found some places where some identifiers defined in `acr.h` conflicted with identifiers in cpp files). 
I haven't unit tested this due to https://github.com/Metaswitch/sprout/issues/1347. I have checked the existing UTs work.
This is surprisingly difficult to live test as its difficult to get a REGISTER to fail in the registrar without also having it fail earlier on. In the end I run the following testcase:
* Set up deployment to not use an I-CSCF. 
* Send REGISTER, receive 401. 
* Kill homestead. 
* Send …

[Reviewer: Andy] Send ACRs when the registrar rejects a REGISTER. 

---

sprout-base.root/usr/share/clearwater/infrastructure/scripts/sprout.monit

Use check-uptime to clear alarms and avoid suprious monit failures.

[Reviewer: None] Use updated check-uptime script.

---

sprout-base.root/usr/share/clearwater/infrastructure/scripts/check-sprout-uptime
sprout-base.root/usr/share/clearwater/infrastructure/scripts/sprout.monit

Monit can't pass arguments to check-program scripts in its current version.

[Reviewer: None] Cope with Monit restrictions

---

src/main.cpp

I needed this for live-test, so I've made the fix.

Fix --nonce_count_supported command-line option name

---

include/as_communication_tracker.h
include/aschain.h
include/scscfsproutlet.h
include/sprout_pd_definitions.h
sprout-base.root/usr/share/clearwater/infrastructure/alarms/sprout_alarms.json
src/Makefile
src/as_communication_tracker.cpp
src/aschain.cpp
src/scscfplugin.cpp
src/scscfsproutlet.cpp
src/ut/as_communication_tracker_test.cpp
src/ut/mock_as_communication_tracker.h
src/ut/scscf_test.cpp

HI Rob, please could you review this change to add AS alarms to sprout? A couple of things to note:
* I tweaked all the S-CSCF UTs to check that AS communication tracker was being invoked correctly. I did this as the tests involve a lot of interesting AS topologies that I wanted to test.  I also decided to add a lot of missing 100 trying flows (from the AS -> Sprout) so that the majority of testcases were treated as AS successes (as that is less confusing).
* I am hoping to add the feature that support requested to log the error reason, but I'll do that as a separate PR. 
Tested in UT so far. I'll test live when you have reviewed the code (or at least gotten far enough through to say "this doesn't need a fundamental re-write").

[Reviewer: Rob] AS alarms

---

include/scscfsproutlet.h
src/aschain.cpp
src/scscfsproutlet.cpp
src/ut/scscf_test.cpp

Hi Rob, please can you review my fix for #1346. This also involves a change to when the S-CSCF calls into the AS comm tracker to make it consistent with the rest of default handling processing. 
As part of this PR, I have removed a number of expectations on the AS communication tracker being called. In retrospect I think adding these to every test was a mistake as they make them too fragile. My change broke most of the tests because they did not include a non-100 response flow, which meant the test treated the flow as an AS failure (when the transaction was torn down at the end of the test). I don't want to 1xx flows to every test case as most of them don't really care about the response. However I have kept the expectations in tests that do interesting things with default handling, and …

Fix up sprout's logic for determining if an AS is responsive

---

include/sproutlet_options.h

This matches the old behaviour, where the default included a port (https://github.com/Metaswitch/sprout/blob/937b339c7949415102fe1332cb9371d8c9c10c43/sprout-base.root/etc/init.d/sprout#L265).
I've run make to confirm it compiles, and I'll test immediately on staging-aio.

[Reviewer: Ellie] Add port to the default Sproutlet URIs

---

src/stack.cpp

When running `sudo service sprout stop` or `sudo service sprout quiesce`, we were seeing the process crash with a signal 11. 
This change should stop this happening.
I have tested this alongside PR #1378 and am in the process of building it to test separately to ensure it fixes the issue on its own. 
This will be a critical fix.

[Reviewer: Rob] Stop crashes on process stop or quiesce

---

mk/sprout.mk
src/sproutletproxy.cpp
src/ut/sproutletproxy_test.cpp

Route subscribe messages over external port rather than sproutlet interface to allow subscription module to process them.
Fixes https://github.com/Metaswitch/sprout/issues/1389

Sproutlet subscribe routing

---

include/pjutils.h
include/sproutletproxy.h
include/subscription.h
src/pjutils.cpp
src/sproutletproxy.cpp
src/subscription.cpp
src/ut/siptest.cpp
src/ut/sproutletproxy_test.cpp

This fixes up the Gemini Subscribe live tests
The change has been to make sure that the selected sproutlet is only rejected if the subscribe would be absorbed by the subscription module. Tested in UTs and the live tests

[Reviewer: ANDY] Fix up Subscribe routing

---

include/connection_tracker.h
include/stack.h
src/connection_tracker.cpp
src/main.cpp
src/stack.cpp

This merges the quiescing thread with the PJSIP transport thread. 
This should avoid a possible deadlock condition. 
The relocation of stack.cpp:L714/753 is to fix crashes that were seen on stopping or quiescing sprout. 
These changes have been tested on a live deployment, and quiescing shows no crashing or locking.
Once https://github.com/Metaswitch/sprout/pull/1344 is merged, it may be worth adding in CHECK_PJ_TRANSPORT_THREAD() before running the quiesce calls, to ensure we are being safe.
Will fix #1351

[Reviewer: Rob] Fix possible deadlock in quiescing

---

include/sprout_pd_definitions.h
src/main.cpp

Don't enforce that a Sprout node must be a P-CSCF/I-CSCF/S-CSCF

[Reviewer: Matt] Remove restriction

---

src/mementoasplugin.cpp

Don't double delete alarms
Part of the fix for https://github.com/Metaswitch/sprout/issues/1408

[Reviewer: Alex] Don't free alarms

---

include/stack.h
src/stack.cpp
src/uri_classifier.cpp
src/ut/siptest.cpp

Fixes #1427.
Tested by running the UTs cleanly and running the live tests against a system running Gemini and Memento that I happened to have lying around.
I've increased the array size to 30 in release-94-fixes and I'm not intending to merge this PR to that branch.

Reviewer MIRW: Change stack_data name array to a vector

---

src/handlers.cpp
src/registrar.cpp
src/scscfsproutlet.cpp
src/subscription.cpp
src/ut/handlers_test.cpp

Along with https://github.com/Metaswitch/cpp-common/pull/512, this fixes #1428.
I've run the UTs cleanly and the live tests.

Reviewer EM: Check whether remote_sdms have servers configured before using them

---

src/enumservice.cpp

This change adds SAS logs to the file-based ENUM code, using the existing "ENUM Complete" and "ENUM Incomplete" logs that would be generated if DNS-based ENUM were in use.
I deliberately refrained from creating a separate SAS log for the "Failed to translate number with regex" case in the interests of simplicity.  Note that an Error log will be made to sprout_current.txt in this case, so the underlying cause can be determined if the operator needs to know.

[Reviewer Alex] Add ENUM success/failure SAS logs to file-based ENUM

---

src/ut/bono_test.cpp

Hi Alex,
This is a temporary fix to https://github.com/Metaswitch/sprout/issues/1429. 
I've renamed the namespace so we no longer get the symbol collision. As it says in the issue, this it a temporary solution. It would be nice to have a common message class, but that's outside the scope of this fix.
Tested that this builds correctly, nothing more.

[Reviewer: Alex] Rename bono_test Message namespace to be unique

---

src/main.cpp

This fixes #1226. I couldn't repro the exact problem, but I've made it so that we always log if the sas server option is missing/invalid.
Tested live
I'll make the same changes to the other SAS'd components as well if this PR is OK.

[Reviewer: Rob] Always make ENT log

---

include/scscfsproutlet.h
src/scscfsproutlet.cpp
src/ut/scscf_test.cpp

This is a fix to some slightly confusing behavior where we occasionally add a session expires header without record-routing ourselves into the dialog. Doing so, while not 'wrong', led to some confusing issues in the field.
I've added some UTs for the correct behavior which now pass. No live testing performed yet.

[Reviewer Alex] Only session_expires with record_route

---

include/bgcfsproutlet.h
include/icscfsproutlet.h
include/scscfsproutlet.h
include/sproutlet.h
src/bgcfplugin.cpp
src/bgcfsproutlet.cpp
src/icscfplugin.cpp
src/icscfsproutlet.cpp
src/scscfplugin.cpp
src/scscfsproutlet.cpp
src/ut/bgcf_test.cpp
src/ut/icscfsproutlet_test.cpp
src/ut/scscf_test.cpp

This change means that we always expose I-CSCF transaction stats, even if I-CSCF functionality is disabled. This gives a more consistent experience when polling differently-configured Sprout nodes for stats.
If this looks OK I'll make the same change for S-CSCF and BGCF, but not MMTel (as we never expect that to be enabled in production).

[Reviewer: Graeme] Always present I-CSCF stats

---

include/connection_tracker.h
src/connection_tracker.cpp

To avoid spam logs in Bono, a check is made in connections_active to see if it is being called on a websockets thread before running the check to see if it is the pjsip transport thread or not. 
To avoid races, the lock has been replaced in this function only. The macro in place in other functions should alert us if we need to replace the lock in any other locations. 
As the websockets thread should behave like a pjsip transport thread, deadlock should not be possible.
Tested on a live deployment, running live tests and connecting/disconnecting a webRTC client. No spurious log outputs were seen, and Sprout/Bono ran without crashes.

[Reviewer: Rob] Fix log-spam from CHECK_PJ_TRANSPORT_THREAD macro in Bono

---

include/as_communication_tracker.h
include/scscfsproutlet.h
include/sprout_pd_definitions.h
src/as_communication_tracker.cpp
src/scscfsproutlet.cpp
src/ut/as_communication_tracker_test.cpp
src/ut/mock_as_communication_tracker.h
src/ut/scscf_test.cpp

At present we have an `AsCommunicationTracker` class that is notified of successful and failed AS communication attempts and raises alarms and ENT logs appropriately. This PR extends this class to allow the user to pass a textual description of the cause of the failure so it can be output in ENT logs, and changes the S-CSCF to supply this description. 
Tested in UT.

[Reviewer: rob] Extend the AsCommunicationTracker to include the failure reason in ENT logs.

---

restund.root/usr/share/clearwater/infrastructure/scripts/restund
sprout-base.root/etc/init.d/sprout
sprout-base.root/usr/share/clearwater/bin/poll_sprout_http.sh

Same as https://github.com/Metaswitch/clearwater-infrastructure/pull/332, but for this repo.

Switch from Python version of bracket_ipv6_address to C++ version

---

src/authentication.cpp

The set_trail call in authenticate_rx_request can only be made if the call to pjsip_tsx_create_uas2 succeeds, as the tsx pointer is still null otherwise

[Reviewer AJH] Only set the SAS trail if UAS tsx create works

---

include/hss_sip_mapping.h
src/Makefile
src/hss_sip_mapping.cpp
src/registrar.cpp
src/subscription.cpp
src/ut/registrar_test.cpp
src/ut/subscription_test.cpp

Treat a server failure (either caused by a failure by the HSS or by a failure
to decode the response) as a SIP 500 Internal Server Error.
Log an appropriate message instead of assuming all failures are caused by
incorrect registration details, including the return code and HSS response
where appropriate.
This fixes #1453 
I've checked that all the UTs pass, and that the two new UTs fail without this code.

[Reviewer: Graeme] Map HSS responses to SIP failure codes correctly

---

debian/bono.logrotate
debian/sprout-base.logrotate
src/main.cpp

Matt, this is the sprout half of the fix to #965.
We use the new function in https://github.com/Metaswitch/cpp-common/pull/531 to add a new logfile for standard out and standard error, and add a logrotate configuration for both files.

[Reviewer: Matt W] Log stdout and stderr to file when a daemon

---

include/cfgoptions.h
sprout-base.root/etc/init.d/sprout
src/main.cpp

This configuration option was undocumented, and isn't supported, so we just hardcode localhost:7253
This fixes #1463

[Reviewer: EM] Disable ability to configure chronos

---

src/main.cpp

Use the common logging and daemonization function in Utils.
Only slightly controversial change is to move init_pjsip_logging down below creating the other loggers, but this looks fine.

[Reviewer: MIRW] Commonalize logging and daemonization

---

src/main.cpp

Matt,
Very trivial fix.
In testing https://github.com/Metaswitch/sprout/pull/1471, I spotted we were actually logging something to stdout. All of the other main options we log using trace instead of fprintf - I think this was overlooked as the conversion from fprintf to trace was done at the same time as this option was added.
Tested by updating the VMWare rig with a deb built using make deb. We then see the following in access_current.txt
04-07-2016 16:23:06.746 UTC Info main.cpp:684: Ralf server set to ralf.vmware.obu-enfield.test:10888
instead of in sprout_out.log.

[Reviewer: MIRW] Log the ralf server using trace instead of fprintf

---

include/registration_utils.h
src/registrar.cpp
src/registration_utils.cpp
src/scscfsproutlet.cpp
src/ut/registrar_test.cpp

This is the fix to Sprout issue #1285

[Reviewer EM] When removing bindings, remove them from remote stores too

---

src/stack.cpp

Make sure all failure paths have ENT logs for UDP transport creation.  (I added one for TCP as well because it was missing).

[Reviewer: RKD] Add ENT logs for UDP transport.

---

src/authentication.cpp

When we fail to do an IMPI SET in memcached we have no hope of processing a challenge response so, send a 503 so we don't get into a REGISTER/401/REGISTER/401 loop.
Tested live and fixes #1404

[Reviewer: RKD] Send a 500 when we fail to store a nonce

---

include/cfgoptions.h
sprout-base.root/etc/init.d/sprout
src/main.cpp
src/ut/basicproxy_test.cpp

Make TCP uplift configurable via the _disable_tcp_switch_ option in local/shared config.
Tested live that the TRC_STATUS in main.cpp is hit when the new option is set.  Tested in UT that that we can set the PJSIP option at runtime.
PJSIP pull request to follow.

[Reviewer: RKD] Make TCP uplift configurable

---

include/cfgoptions.h
include/enumservice.h
sprout-base.root/etc/init.d/sprout
src/bgcfsproutlet.cpp
src/enumservice.cpp
src/icscfsproutlet.cpp
src/main.cpp
src/pjutils.cpp
src/scscfsproutlet.cpp
src/ut/enumservice_test.cpp
src/ut/icscfsproutlet_test.cpp
src/ut/scscf_test.cpp

TS 24.229 says "Upon an unsuccessful user location query when the response from the HSS indicates that the user does not exist, and if the Request-URI is a tel URI containing a public telecommunications number as specified in RFC 3966 [22], the I-CSCF may support a local configuration option that indicates whether or not request routeing is to be attempted. If the local configuration option indicates that request routeing is to be attempted, then the I-CSCF shall perform one of the following procedures based on local operator policy:
1)	forward the request to the transit functionality for subsequent routeing; or
...[ENUM lookup alternatives follow]"
I thought that would be useful functionality to have, so I've implemented a mode where you can turn off ENUM entirely and the I-CSCF will …

[Reviewer: Ellie] Add ability for the I-CSCF to handle failed HSS lookups by routing to a transit function

---

src/bgcfsproutlet.cpp
src/ut/bgcf_test.cpp

In my testing, I hit a case where a message arrived at the BGCF with Route headers still attached. This meant that when the BGCF added Route headers, the message still followed the pre-existing ones.
I don't think that's sensible behaviour, so I've added code to strip all existing Route headers when we start adding BGCF routes. I've tested that this works.
I'll talk to you tomorrow about the exact flow that triggered this, for background.

[Reviewer: Ellie] Remove existing Route headers before the BGCF adds them

---

src/custom_headers.cpp
src/ut/custom_headers_test.cpp

Fixes a problem whereby the (valid) header "Accept-Contact: *" was being rejected by parse_hdr_accept_contact.
Tested live using an OPTIONS message with the above header.  Custom header UTs pass.  I decided not to write a new UT to cover this case - let me know if you think thats the wrong call.

[Review AJH] Allow for minimal Accept-Contact header

---

src/main.cpp

Removal of a few 'if' statements so that the alarms and comm links are always enabled, instead of only being enabled if I/S-CSCF functionality is enabled.
Please note - **this is not yet ready for review by the Clearwater team.** This code will first be internally reviewed by JAG2's team.
Furthermore, the changes shown below initially look horrible - the only changes are the removal of three 'if' statements, their associated braces, and reducing the indentation of the code they contained. Unfortunately, it would appear that these changes are causing problems for the comparison.
The code has been tested, and all Sprout UTs and the full suite of live tests all pass.

Alarms, comm links all always enabled

---

clearwater-sip-perf.root/usr/share/clearwater/bin/sip-perf
clearwater-sip-perf.root/usr/share/clearwater/sip-perf/sip-perf.xml
clearwater-sip-stress.root/usr/share/clearwater/sip-stress/sip-stress.xml
debian/control

I ran clearwater-sip-perf on an all-in-one node - here are the fixes I needed to make that work.
* clearwater-sip-perf was marked as conflicting with sprout/bono/restund, but actually it runs fine.
* the home domain (example.com) doesn't resolve on an AIO node, so I gave sip-perf an optional argument which is the IP to run stress on.
* if a 100 Trying came in after the INVITE, we'd use its Record-Route headers on subsequent messages - but as 100s aren't end-to-end this meant in-dialog messages got misrouted. We already had some stuff to make this work for Via headers which I've just extended.

[Reviewer: Matt] Minor perf-test fixes

---

debian/restund.init.d

If we don't specify the executable, start-stop-daemon will kill the init script.
This fixes issue #1509.
I've tested this live and verifies that this fixes this issue. I've tested both with and without a running restund, and checked that the PID of the restund process changed, and that there wasn't one left behind.

[Reviewer: RKD] Stop restund properly

---

include/scscfsproutlet.h
src/Makefile
src/scscfsproutlet.cpp
src/ut/fakesnmp.cpp

I'm going to live test by:
- making a single call
- checking that the stats are updated, and that the recorded latency approximately matches the latency in SAS
- running the live tests and checking that this stat still looks sensible
I'll load up the MIB and use snmptable to check this, so I check that the MIB and the stat match.

[Reviewer: Adam] Track the time from INVITE to 180 Ringing

---

Makefile

The root makefile builds submodules recursively by calling make build in each plugin directory. However, including cpp.mk provides a make all, but not a make build-target. To make these slightly more consistent, I propose simply calling make in the plugin directory for the build, allowing the plugin itself to specify the default target.

Build submodules with "make" rather than "make build"

---

include/custom_headers.h
src/custom_headers.cpp
src/mmtel.cpp
src/ut/scscf_test.cpp

Modified the privacy header code to use a semicolon delimiter rather than commas, see issue #1514. The changes are:
1) Added parse and print functions for a privacy header to custom_headers.cpp and custom_headers.h
2) Modified the mmtel code to call the privacy header constructor rather than construct a generic array header.
This commit must be used in conjunction with the corresponding privacy_header branch of pjsip, for which a corresponding pull request will be made

[Reviewer: RJW2] Privacy header now splits on semicolons rather than commas.

---

debian/clearwater-sip-stress.init.d

The clearwater-sip-stress script does not correctly kill the sip-stress process in the case that it is not caught when killing processes in the relevant pidfile. This pull request covers fixing this problem.

Fix bug in script stopping sipp-stress

---

src/custom_headers.cpp

Instead of changing the vptr table for all generic array headers,
instead provide a different vptr table for privacy headers.
This fixes a bug introduced in https://github.com/Metaswitch/sprout/pull/1521 whereby we will incorrectly print headers (e.g. Supported) if we've created a Privacy header - we end up printing: `Supported: replaces; norefersub; extended-refer; timer; X-cisco-serviceuri` instead of `Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri`
This requires the separately assigned https://github.com/Metaswitch/pjsip-upstream/pull/50 change.
I've tested by running the tests - need to investigate why this doesn't always cause failures.

[Reviewer: RKD] Fix header printing

---

sprout-base.root/etc/init.d/sprout
src/mementoasplugin.cpp

If we're using memento and `cassandra_hostname` is set, add it to memento's plugin options.  When the memento plugin connects to cassandra, use `cassandra_hostname` (if it is set) in preference to `localhost`.
Tested that the plugin can connect to a remote cassandra using the live tests.

[Reviewer: RKD] Add cassandra hostname option for memento plugin

---

src/bono.cpp

When bono statelessly rejects a request it does not add start and end time markersm, which means the trace cannot be displayed in SAS. 
I've tested this by hacking clearwater-live-test to make a call without registering the caller (which causes bono to statelessly reject with a 403). Before the change the call did not appear in SAS results but after the change it did.

[Reviewer: Graeme] Add start and end markers when bono statelessly rejects a request

---

src/Makefile

This fixes the following error when trying to start sprout using commit [94ad54](https://github.com/Metaswitch/sprout/commit/94ad54da9be24b94e3f39d8bb32ae63aa9300c51)
26-09-2016 14:05:53.785 UTC Error pluginloader.cpp:148: Error loading Sproutlet plug-in /usr/share/clearwater/sprout/plugins/memento-as.so - /usr/share/clearwater/sprout/lib/libcassandra.so: undefined symbol: _ZN6apache6thrift12GlobalOutputE
The error happens because memento-as.so loads libcassandra.so, which depends on _ZN6apache6thrift12GlobalOutputE that should be provided by libthrift.so. Thrift used to be loaded by memento-as.so, but this stopped happening when we introduced the cassandra connection pooling stuff. 
Fix is to build memento-as.so with cassandra_connection_pool.so

[Reviewer: Seb] Build memento with the cassndra connection pool

---

debian/bono.init.d

Testing of a Clearwater deployment with an IBCF showed that whenever the IBCF was routed to via domain, rather than IP, the node would not remove its own route header and would hence attempt to route to itself.
@mirw suggested that this could be fixed by changing the alias argument in Bono's init.d configuration. I have changed it from the public IP to ibcf.<zone>, which is the expected IP to be used for a cluster IBCF domain entry.
I have tested this change and verified that it fixes the issue I encountered, without breaking the core Bono functionality. 
Please let me know whether you're happy with this change. Ellie, if you're not the right person for this or if you're too busy to take this right now, please pass it to the appropriate person (or let me know who to pass it to). Thank you

[Reviewer: Ellie] [INT-54] Changed bono alias to domain, to allow for routing to ibcf by domain

---

include/uri_classifier.h
src/icscfsproutlet.cpp
src/pjutils.cpp
src/scscfsproutlet.cpp
src/uri_classifier.cpp
src/ut/icscfsproutlet_test.cpp
src/ut/uriclassifier_test.cpp

This addresses a couple of problems in our handling of terminating requests that contain NP data.  
-  If a terminating request arrives at the I-CSCF with a global telephone SIP URI that contains NP data, we don't convert it to a Tel URI (and don't perform an ENUM lookup) because we are looking for a GLOBAL_PHONE_NUMBER and we get (FINAL_)NP_DATA from classify_uri
-  If a terminating request arrives at the S-CSCF with a global telephone SIP URI that contains NP data, classify_uri gives us (FINAL_)NP_DATA and we reject the request because we don't see NODE_LOCAL_SIP_URI or HOME_DOMAIN_SIP_URI.
Note that there is an alternative fix here, which is to recognize that NP data is effectively orthogonal to other types of classification and to return it as a three valued output param …

[Reviewer: AJH] Only check for NP data in URI classification when this is more important than domain-based classification

---

debian/control
debian/sprout-base.postinst
include/handlers.h
include/hssconnection.h
include/registration_utils.h
include/subscriber_data_manager.h
sprout-base.root/usr/share/clearwater/infrastructure/scripts/create-sprout-nginx-config
src/handlers.cpp
src/main.cpp
src/registration_utils.cpp
src/subscriber_data_manager.cpp
src/ut/handlers_test.cpp
src/ut/mock_hss_connection.h

Hi Matt, please can you review this change to add an HTTP management API to sprout to allow users to query a subscriber's bindings and subscriptions, and to administratively deregister them.
I've tested this in UT, and also live:
* Try to get the bindings/subscriptions for a subscriber who isn't registered.
* Get the bindings/subscriptions for a subscriber who *is* registered.
* Administratively deregister a subscriber, and check that a dereg request is sent to homestead. 
Graeme is doing a fuller live test.

[Reviewer: Matt] Add management cached data APIs

---

src/main.cpp

Fixes a but where bono was listening on port 9888 as well as sprout, which breaks the AIO node. Tested live:
* Sprout is listening on port 9888 and 9886 (via nginx in the latter case) and responds to the ping URL on both interfaces. 
* Bono is not listening on port 9888.

[No review required] Only bind sockets if S-CSCF is enabled

---

include/cfgoptions.h
include/hssconnection.h
sprout-base.root/etc/init.d/sprout
src/hssconnection.cpp
src/main.cpp
src/ut/fakehssconnection.cpp
src/ut/fakehssconnection.hpp
src/ut/scscf_test.cpp

We don't support wildcard matching yet, but one thing that's quite common is to have wildcard PSIs, where we do a lookup for +1234 and get back a single IFC for +123!*!.
We don't need wildcard matching support to handle this - all we need to do is assume the IFC the HSS gave us is the one we're meant to have, even if the Identity field doesn't match.
This PR adds a command-line option to make that assumption (I haven't assumed it by default, because it could do the wrong thing in some situations, e.g. if we had multiple IFCs).
Not urgent.

[Reviewer: Ellie] Add an --allow-fallback-ifcs option to enable more wildcard use-cases

---

include/cfgoptions.h
sprout-base.root/etc/init.d/sprout
src/main.cpp

rather than just using the configured sprout hostname for chronos callbacks.
This allows us to configure chronos to always call back to sprouts in the local
site
Testing done:
- live tested

[Reviewer: Ellie] Add chronos-sprout-callback-uri option

---

include/analyticslogger.h
include/sprout_pd_definitions.h
scripts/sprout-log-cleanup
sprout-base.root/etc/logrotate.d/sproutanalytics
sprout-base.root/usr/share/clearwater/infrastructure/scripts/create-analytics-syslog-config
src/Makefile
src/analyticslogger.cpp
src/main.cpp
src/ut/authentication_test.cpp
src/ut/bono_test.cpp
src/ut/registrar_test.cpp
src/ut/scscf_test.cpp
src/ut/subscription_test.cpp

Use syslog to log analytics logs.
This also contains the Sprout changes that match https://github.com/Metaswitch/cpp-common/pull/574.

Reviewer RKD: Use syslog for analytics logs

---

src/authentication.cpp

Rob,
As discussed, here's a fix to our AKAv2 support.
I haven't add any new UTs - I had a look, but the current tests fall through to looking at the challenge instead, so it still works. I don't think there's anything sensible to do here. I could send in an authentication request where we've replied invalidly to a challenge (i.e we were challenged with DIGEST, but respond with AKAv2), but that feels wrong. As such, I suspect this fix has no impact in a real deployment.

[Reviewer: RKD] Recognize AKAv2 when choosing stats table for auth

---

src/connection_tracker.cpp
src/main.cpp
src/quiescing_manager.cpp
src/stack.cpp

Add more quiescing logs so that we know exactly where we hang the next time we hit #1530 
I've added status logs throughout to make sure we see them even with log_level=2.  I think this covers the whole quiescing flow.

[Reviewer: RKD] Add more quiescing logging

---

src/bgcfsproutlet.cpp
src/ut/bgcf_test.cpp

Route phone number URIs with no routing number parameter on the phone number.
Previously, they were always routed to the wildcard domain route. Now, try to route on the phone number. If no matching routes found, fall back to the wildcard domain as before.
**Testing done:**
- unit tests

[Reviewer Alex] BGCF Routing by phone number

---

sprout-base.root/usr/share/clearwater/infrastructure/scripts/create-analytics-syslog-config
src/analyticslogger.cpp

I was printing the contents of the log and the timestamp the wrong way around. This also exposed the fact that my logs had an (unnecessary) new line in them, which was now being printed out (as #012).
I've also added a random comment.

Reviewer MGM: Analytics logs minor fixes

---

src/main.cpp

In testing https://github.com/Metaswitch/clearwater-infrastructure/pull/393, and investigating why sprout wouldn't build with the hacked in change for forcing 503 returns, i found that there was no load monitor on the signaling http stack. 
This meant that even when overloaded, sprout would not return a 503 to the poll-http script.
To test that this works, i altered https://github.com/Metaswitch/cpp-common/blob/54371f20e89c60a04218bdeebe90d687f26345fc/src/httpstack.cpp#L313 to test `!(_load_monitor->admit_request(trail)`, forcing overload while testing the load monitor.
This has not been tested on a system under significant load

[Reviewer: Ellie] Add load monitor to the http stacks.

---

src/basicproxy.cpp

Hopefully this is an uncontroversial fragment extracted from the various transport-related hacks that John made.
I don't know what exactly went wrong without this fix, but the PJSIP docs do say that users should prefer to call `pjsip_tsx_set_transport`, rather than `pjsip_tx_data_set_transport` directly, and this looks sensible enough.
Unit tests don't fail regardless of the state of this code (though it is covered) - if you can think of a likely testcase that would prove why this is necessary, let me know.

use already-selected transport for CANCEL

---

include/sproutletproxy.h
src/sproutletproxy.cpp
src/ut/sproutletproxy_test.cpp

@chris-elford-metaswitch flagged that the does_uri_match_sproutlet function was quite long could be simplified (after he looked at it for a mailing list issue).
I've pulled the function to extract service names out into a separate function, and deleted the checking of the "services" parameter (based on the comment "LCOV_EXCL_START - not currently supported").

[Reviewer: Ellie] Make Sproutlet matching code more concise

---

src/authentication.cpp
src/ut/authentication_test.cpp

This fixes #1599.
We fix this by using the known string length, rather than just up until the first null byte when we have decoded the hex from Homestead. I've added a UT for handling null bytes in a response, which fails before this fix, and succeeds afterwards.
This also fixes the other issue Rob spotted, where if the digest includes a null byte, we'll fail to handle the request correctly. It also fixes an issue where the buffer given to us by OpenSSL isn't totally guaranteed to be null terminated (but probably is).
This needs https://github.com/Metaswitch/pjsip-upstream/pull/52 for the pj_strdup4 function.

[Reviewer: Ellie] Handle digests and keys with null bytes in them

---

src/sproutletproxy.cpp

...so that we don't crash when we get a route header in without a period.
This change fixed the UT failure I was seeing in the subscription sproutlet.

[Reviewer: AJH] Check separator is not NULL

---

src/ut/contact_filtering_test.cpp

Merging #1597 damaged code coverage (which is very interesting... I guess the old bogus code was being optimised away and then nothing could tell that we weren't hitting it).
This tweak varies the priority in some unit tests so that we do now hit all code branches.  
NB Per the existing testcases, we don't actually check that the comparison gives the right answer!  I propose that fixing that is out of scope for this pull request.
Alex - sending to you since you merged #1597 for me.

Vary priority of bindings, for code coverage

---

docs/Mangelwurzel.md
src/main.cpp
src/mangelwurzel/mangelwurzel.cpp
src/mangelwurzel/ut/mangelwurzel_test.cpp

This:
* gets Mangelwurzel to respond with 200 OK to REGISTER requests, allowing us to take standard IFCs and swap in Mangelwurzel's URI
* gets Mangelwurzel to recognise itself in the Request-URI as well as the top Route header, as that's how REGISTER requests to app servers are formed (this required changing a lot of indentation, sorry)
* removes two checks in main.cpp that don't make sense (one is that you must have a Homestead unless you set `authentication=N`, which doesn't make sense for app-server-only nodes, and the other is that you must have a Homestead URL if you have a Homer URL, which is fine for Mangelwurzel but doesn't make sense for MMTel AS)
* there is a check that you must have a Homestead URL if you're an I-CSCF or S-CSCF, so I think these checks are redundant

[Reviewer: Graeme] Allow Mangelwurzel to handle REGISTER requests

---

include/scscfsproutlet.h
src/scscfsproutlet.cpp
src/ut/scscf_test.cpp

This is supposed to track the number of additional INVITEs sent because a target has multiple bindings, e.g. if a user has 3 registered devices then the stat is incremented twice per call, and it is not incremented if a user has only 1 registered device.

[REVIEWER: Ellie] Add a stat to track forked INVITEs due to multiple bindings.

---

include/authenticationsproutlet.h
include/cfgoptions.h
include/forwardingsproutlet.h
include/registrarsproutlet.h
include/sproutlet.h
include/sproutletproxy.h
include/subscriptionsproutlet.h
src/Makefile
src/authenticationsproutlet.cpp
src/forwardingsproutlet.cpp
src/main.cpp
src/registrarsproutlet.cpp
src/scscfplugin.cpp
src/scscfsproutlet.cpp
src/sproutletproxy.cpp
src/subscriptionsproutlet.cpp
src/ut/authentication_test.cpp
src/ut/mocktsxhelper.h
src/ut/registrar_test.cpp
src/ut/scscf_test.cpp
src/ut/sproutletproxy_test.cpp
src/ut/subscription_test.cpp

This PR contains the code to plumb the new authentication, registrar and subscription sproutlets together with the existing S-CSCF proxy sproutlet. Please can you review:
* @sathiyan-sivathas please can you be the primary reviewer
* @eleanor-merry please can you cast you eyes over this and check it matched what we discussed. 
I have checked that all the UTs run, as do all the tests in clearwater-live-test (except the B2BUA test which I think might be just broken - though I'll check this when I'm back after Christmas).
You'll see that I have not removed the ability for the sproutlets to specify what ports and URis they want to register. Instead the SCSCF plugin just does not configure these. This is for two reasons:
1. Removing the URi and port makes the sproutlets really awkward to UT in …

Sproutlet refactor integration

---

sprout-base.root/etc/init.d/sprout

listen_port is an old configuration option which specifies a port to be used for all sproutlets. This PR re-adds the option, as it is currently the easiest way to specify a port for a node only running a single, non-default sproutlet.

[Reviewer: EM] Re-added listen_port to config options

---

include/sproutlet_options.h
src/main.cpp

Following from pull request #1672, this removes the listen_port functionality from sproutlet_options so that it does not affect default sproutlets. This is replaced by a block in main which, if listen_port is set, adds the port to the list of ports to be configured. This allows for listen_port to be used to specify a port to be configured for non-default sproutlets without affecting any default sproutlets.

[Reviewer: EM] Move listen_port from sproutlet_options to main

---

src/basicproxy.cpp

As discussed, this is the small fix for send_request.
Just want to run this quickly by you in case it isn't what you were expecting. If you're happy i'll merge down and talk to Rob about system testing it properly. In the process of building it for a quick chef deployment test to make sure it isn't somehow completely broken.
I have opened #1687  to cover further checking in e.g. `retry_request`, to make sure that there aren't further window conditions.
As the issue states, the only location other than `retry_request` where we check the return value of `pjsip_tsx_send_msg` results in us writing a log if it fails, and so is not a serious concern; `retry_request` will want investigation, but as discussed, we are much less likely to hit any error there, as it is already in a retry branch.

[Reviewer: Matt] Ignore PJ_FAILURE from pj_tsx_send_msg in send_request

---

src/basicproxy.cpp

@rkd-msw 
This log should hopefully be triggered only when we encounter the synchronous failure in pjsip_tsx_send_msg, which was leading to the failures seen in #1607 .
I'm going to merge all the way down to dev, just to keep commits in line, so as and when you've tested this all i'll revert the change in a new commit if we decide we don't want to keep this log in.

[No reviewer] Add log to track hitting window condition

---

src/scscfplugin.cpp

It looks like when refactoring the SCSCF modules into sproutlets, we broken the reg-max-expires config option that controls how log a device can register for. Please can you review my (simple) fix. 
I ran into this problem when running the P-CSCF-emulating stress tests (the tests try to register for 1hr, but were only registering for 5mins so some calls didn't work). I've checked that with this fix (and an appropriate value for reg_max_expires) the tests now work.

Fix SCSCF plugin to correctly configure reg-max-expires

---

debian/bono.init.d
debian/restund.init.d
sprout-base.root/etc/init.d/sprout

If the abort command fails to kill a process, we attempt to remove the pidfile. 
This is to combine with https://github.com/Metaswitch/clearwater-monit/pull/47, to allow us to resolve #1326 . 
If there is no process running with the pid provided in the pidfile, and matching the expected process name, the abort will fail. We already have code in place to kill rogue processes that match on name, but not on pid. Removing the pidfile allows monit to realise the process is dead if we hit the referenced race condition, and kick off starting the process up again.
If you're happy with this I will go around and make the same change to the init.d scripts for our other processes.

[Reviewer: Ellie] Have the init.d abort remove pidfile if it fails

---

src/basicproxy.cpp

Removing the log added in https://github.com/Metaswitch/sprout/pull/1691, as confirmed that we resolved that window condition in https://github.com/Metaswitch/sprout/issues/1607

[No Reviewer] Remove temporary log

---

include/subscriber_data_manager.h
src/subscriber_data_manager.cpp
src/subscription.cpp
src/ut/mock_analytics_logger.h
src/ut/subscriber_data_manager_test.cpp
src/ut/subscription_test.cpp

Three parts to this...
- Fix REGISTER audit log issues introduced by https://github.com/Metaswitch/sprout/pull/1585/files 
-  REGISTER audit log expires value should be the time interval (e.g. 300s).  The PR above inadvertently changed this to be the epoch time at which the register will expire
- de-REGISTER should be logged as a REGISTER with expires=0.  The PR above inadvertently changed this so that it was the previous expiry time (i.e. the logs for a REGISTER and subsequent de-REGISTER were identical).
- Add UTs so that we don't break this again so easily in future.
- Adding UTs for Subscriptions to match those for Registers reveals that we are writing Subscription audit logs on both the primary and backup SDM.   This is inconsistent with what we do for Registers so fix it.

Fix Sprout analytics logs

---

src/basicproxy.cpp

See analysis of the issue / fix in Issue #1699 
Fixed the issue plus another case where I believe (from code reading) that we currently don't correctly release the group lock in an untested error case.
Huw has retested and the fix is good.   (original issue he hit was caused by mismatched binaries)

[Reviewer: Matt] Fix segfault due to late CANCEL window condition

---

src/bgcfsproutlet.cpp
src/ut/bgcf_test.cpp

Fallback to wildcard domain route if there is one, if a phone number with routing number parameter doesn't match any configured phone number routes.
This ensures that the URIs tel:xxx and tel:yyy;rn=xxx will be routed the same.
There is a readthedocs change too in https://github.com/Metaswitch/clearwater-readthedocs/pull/241
- UTs added and verified they failed before the change and pass after.

[Reviewer: Ellie] BGCF phone number routing

---

include/constants.h
include/scscfsproutlet.h
src/scscfsproutlet.cpp
src/ut/scscf_test.cpp

This is a fix to issue #1667.  
- Previous log wasn't harmless (good spot @rkd).   We were actually generating billing-records for interim hops where we shouldn't have been, and furthermore we were incorrectly marking them as originating when some where in fact terminating.
- Fix is, when record-routing, to explicitly make routes as charge-none if we don't want to generate billing records for that hop, and then when processing an in-dialog request not generate an ACR if the top route header indicates charge-none.   We could have just done this when there was no billing-role specified, but this way is more explicit and allows us to continue to generate a warning if we get a request with a route header that doesn't correctly identify a billing-role.
UTs test that we correctly use …

Use billing-role none to suppress unwanted ACRs

---

src/main.cpp

If we start before we bind to the socket, there's a race condition where the
worker threads might start before we've bound the socket, and in that scenario
they seem to be unable to handle the http requests.
This is what we do for all the other components that use the HttpStack, so it looks like the right thing to do.
This is a fix for issue #1713 
- live tested

[Reviewer: Ellie] Only start the http stacks after we've bound the socket

---

include/sproutlet.h
include/sproutletproxy.h
src/forwardingsproutlet.cpp
src/scscfsproutlet.cpp
src/sproutletproxy.cpp
src/ut/authentication_test.cpp
src/ut/scscf_test.cpp

Fixes #1696 
As discussed in the whiteboard, this change:
- Strips the user part off the header that caused us to route to sprout before building a route header to route between sproutlets.
- Specifies a service parameter in the odi route header added by the scscf-proxy.
This fixes the bug where we hit the max-forwards limit if a sproutlet is specified the route header and also makes sure that the scscf-proxy can still see the odi token for requests that come back from app servers.
UTs pass, but I need to check the live tests before I merge.

[Reviewer: AJH] Sproutlet routing robustness

---

src/thread_dispatcher.cpp

Add maybes to the reported Call-ID and CSeq when we've hit an exception (as we can't rely on them being accurate).

[No reviewer] Add maybes

---

src/connection_tracker.cpp

I'd made it STATUS when I was tracking down a quiescing bug; this shouldn't have been checked in.

[No reviewer] Make connection tracker log debug again

---

include/acr.h
src/acr.cpp
src/scscfsproutlet.cpp

The RalfACR can be accessed by multiple SCSCFSproutletTsxs, so we need to add locking.
This is a fix for issue #981 
- tested on a machine that was hitting this crash under load before, and now doesn't

[Reviewer: Ellie] Add locking to RalfACR

---

sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_bgcf_json
sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_enum_json
sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_json
sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_scscf_json

Fix according to Rob's suggestion in https://github.com/Metaswitch/clearwater-etcd/pull/409#issuecomment-281081813
In /usr/share/clearwater/clearwater-config-manager/scripts/upload_json, check if the file size is larger than specified (10KB) while NOT using third argument --allow-large. If so, print an error message and exit early.
Tested in real system by uploading a 7KB and 14KB enum.json (using upload_enum_json) and getting the key to see if the upload is successful. 7KB worked, 14KB threw the error message, and 14KB with --allow-large set in the upload_enum_json worked.
#1741

[Reviewer: Adam]Check upload json file size & Allow large file using third argument

---

include/enumservice.h
src/enumservice.cpp
src/ut/enumservice_test.cpp
src/ut/test_enum_prefix_matching.json

UT: added a json file where the more specific prefix comes later, test that EnumService is matching to the more specific prefix.
Implementation: current implementation uses a vector containing Pfix, I added a Map containing (prefix, Pfix) and do the matching search using the map, as Map is ordered by key length.
UT passed. 
#1609

[Reviewer: Adam]Enum prefix matching

---

src/enumservice.cpp
src/ut/enumservice_test.cpp
src/ut/test_enum_strip_separator.json

Fixed #1622 to allow visual separators in enum json file, by using the same strip-separators functions as used in bgcfservice. Tested.

[Reviewer: Adam] Enum visual separators

---

include/mangelwurzel/mangelwurzel.h
src/mangelwurzel/mangelwurzel.cpp

I saw loads of messages like this in Mangelwurzel's logs:
```
19-02-2017 22:00:00.020 UTC Warning sproutletproxy.cpp:1184: Sproutlet mangelwurzel-0x7feeb01657d0 leaked 1 messages - reclaiming
19-02-2017 22:00:00.020 UTC Warning sproutletproxy.cpp:1187:   Leaked message - Request msg PRACK/cseq=2 (tdta0x7fee70253900)
19-02-2017 22:00:00.023 UTC Warning sproutletproxy.cpp:1184: Sproutlet mangelwurzel-0x7fee7c203e40 leaked 4 messages - reclaiming
19-02-2017 22:00:00.024 UTC Warning sproutletproxy.cpp:1187:   Leaked message - Request msg INVITE/cseq=1 (tdta0x7fee78020550)
19-02-2017 22:00:00.024 UTC Warning sproutletproxy.cpp:1187:   Leaked message - Request msg INVITE/cseq=1 (tdta0x7fee70048210)
19-02-2017 22:00:00.024 UTC Warning sproutletproxy.cpp:1187:   Leaked message - Request msg …
```

[Reviewer: Graeme] Don't call original_request within Mangelwurzel

---

include/scscfsproutlet.h
src/scscfsproutlet.cpp
src/ut/scscf_test.cpp

Turn a 500/503 error from homestead when looking up IFCs into a SIP 504 error.
This only covers this specific case, not the more general problem of turning HTTP error codes into the correct SIP error code. We think we should be doing this kind of thing more generally, but we don't want to be making such a wide-reaching change at this point.
So the plan is to merge this to release-114-fixes and then dev, and then raise an issue against dev to ensure we look at a fuller fix for this in future.
- UTs added to check we're sending a 504 in the 2 places that it was added
- manually live tested to ensure we actually send a 504 when we get a 503 response from homestead for the HTTP PUT that we send as part of the INVITE flow to set up a call
- clearwater-live-tests run over a deployment including …

[Reviewer: Adam] Better SIP error code on 500/503 from homestead

---

sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_json

As @huws pointed out, removed a space between "ALLOW_LARGE_UPLOADS" and "=" and changed the variable reference to using the right name.

Fixed minor bugs for the check-upload-json-size commit Issue 1747.

---

include/scscfsproutlet.h
src/scscfsproutlet.cpp
src/ut/scscf_test.cpp

Previously we had an issue where if a session continued AS was bypassed, the onward request didn't have the correct record route headers. This is because we record-route when determining the served user, but then call `original_request` when retrying to the next AS. 
I've fixed this by saving off the request when the S-CSCF record-routes itself, and using this request as a baseline when bypassing an AS. 
I've reproduced the original error in UT, and used this to checked the fix works.

Fix up record-routing for AS default handling

---

sprout-base.root/usr/share/clearwater/infrastructure/scripts/create-analytics-syslog-config

This should mean that users can modify the config file created, and then not lose those changes when cw-infra restarts. 
Seem reasonable?

[Reviewer: Richard] Update analytics generation to not override user changes

---

src/ut/common_sip_processing_test.cpp

Rob,
Could you review this change to the tests for the Supported: header with a trailing comma?  Passing direct to you since you've looked at this already - hope that's OK.
Note that I have not run the live tests against this fix as it seems fairly minor.  Let me know if you think I need to run them before releasing.
Neil

[Reviewer: RKD] Allow list headers to have a trailing comma

---

scripts/sprout-log-cleanup

Rob,
This changes the log cleanup script for sprout so that we limit the number of sprout access logs, and set a count limit on the analytics logs.
Note, this is still quite broken in a number of ways, but I'll address this in a separate change for dev only.
This partially reverts the change to log cleanup made in https://github.com/Metaswitch/sprout/pull/1572 and partially fixes the issues seen under https://github.com/Metaswitch/sprout/issues/1783

[Reviewer: Rob] Clean up access logs and limit analytics logs

---

mk/thrift.mk

This fixes issue #1786.
Thrift by default has bindings for a whole load of languages. If you attempt to build Sprout on a platform with npm installed, it attempts to create Javascript bindings. This can fail, and given we don't need them, it's easiest to just disable support for npm (and lua while we are here, as we don't need that either).

[Reviewer: Seb] Disable lua and nodejs support in thrift

---

mk/curl.mk

If we don't do this, we need to install extra libraries (librtmp, libldap liblber) to nodes running Sprout in order to ensure they run correctly.
As we don't need these protocols, we should just disable them at configure time.

[Reviewer: Seb] Don't configure LDAP or RTMP for curl

---

include/basicproxy.h
include/sproutlet.h
include/sproutletproxy.h
src/basicproxy.cpp
src/sproutletproxy.cpp
src/ut/mocktsxhelper.h
src/ut/sproutletproxy_test.cpp

NOT FOR MERGING!
The ugliest part of our transport hacks: re-use incoming transport for outgoing messages.
John dabbled with making this configurable per application server but didn't get this into any sort of useful state, and I'm not convinced that it's the right scope to configure this anyway.  So I've removed that code from this diff.
I think I'd prefer to control this by a global config option whose meaning is basically "we're acting as an app server for a non-IMS call agent" (maybe we can come up with something that doesn't sound _quite_ so specific).  But definitely up for discussion.

reuse incoming transport

---

mk/curl.mk

Seb,
This fixes the problem building Sprout you were seeing on Friday.
Curl doesn't build when not linking to libldap if we don't manually specify that we need to link to libdl.
This is an upstream bug in curl's configure script -
https://curl.haxx.se/mail/lib-2009-10/0375.html
It's not entirely clear to me why this does work when you *do* link to libldap without specifying "-ldl" anywhere.

[Reviewer: Seb] Link to libdl when building curl

---

src/main.cpp

TS 24.229 suggests the P-CSCF should send a higher subscription max expiry than
the registration. Thus we default the max subscription expiry to a higher value.
RFC 3680 suggests 3761 for an expiry of 3600, so we just add 161 seconds to the registration max expiry.

[Reviewer: Ellie] Include margin in default subscription expiry.

---

src/main.cpp

Seb,
This fixes our parsing of Sprout options so that we break after we've parsed the callback URI for Chronos.

[Reviewer: Seb] Correctly break after chronos callback URI

---

sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_json

Hi Rob
Can you review this tweak to https://github.com/Metaswitch/sprout/pull/1803 to emit the error text from json.tool to the screen?
Tested live against a deliberately broken enum.json file, and the upload_enum_json tool now emits, e.g.
"The configuration file at /etc/clearwater/enum.json contains invalid JSON.
Expecting , delimiter: line 7 column 5 (char 173)
Please provide a valid configuration file, and re-run the command"
(I deleted one of the square brackets in the file.  line7 column 5 is the location of the mismatched remaining bracket)

[Reviewer RKD]: Emit json.tool output to screen to aid problem determination

---

src/pluginloader.cpp

Seb,
Currently there is a couple of scenarios where a Sprout plugin can fail to load, but Sprout still continues to run, without the plugin functionality.
This can make it possibly to upgrade a plugin (e.g. the BGCF sproutlet) and break the functionality if the new BGCF fails to load without any alarms being fired, and with monit reporting that everything is working correctly.
This fix resolves that:
- We now mark the plugins as having failed to load if `dlopen` fails on one of the .so files.
- We now mark the plugins as having failed if for a plugin we are unable to get a handle to the sproutlet plugin reference.
- We now mark the plugins as having failed to load if any of the sproutlets are using an unsupported API version.
There's no UTs for this code.
If we fail to load a plugin, we …

[Reviewer: Seb] Abort if a plugin fails to load in any way.

---

src/sproutletproxy.cpp
src/ut/sproutletproxy_test.cpp

This updates the `rx_fork_error` function so that we log a failure to the outgoing SIP transactions table.
This fixes an issue where we don't log transaction failures in the cases of hitting a transport error or the request timing out.

[Reviewer: AJH] Increment sproutlet tsx failure stat on timeout or transport failure

---

src/sproutletproxy.cpp
src/ut/authentication_test.cpp

Turns out I found the right fix for this.
The live tests fail because the odi token is stripped when routing from the AS via the other sproutlets to the S-CSCF. We need to make sure we don't do that.
I also needed to disable a test that didn't make sense anymore.

[Reviewer: SR2] Preserve the user part when routing between sproutlets

---

include/hssconnection.h
include/icscfrouter.h
src/hssconnection.cpp
src/icscfrouter.cpp
src/icscfsproutlet.cpp
src/ut/hssconnection_test.cpp
src/ut/icscfsproutlet_test.cpp

Converts the "sos" parameter in the contact header of a register to the "sos=true" parameter on the UAR HTTP GET request to homestead.
Together with Metaswitch/homestead#446 this adds support for signalling to the HSS on the UAR that we are handling an emergency REGISTER.

[Reviewer: KH1] Pass through the sos flag on UAR

---

include/pjutils.h
include/thread_dispatcher.h
src/pjutils.cpp
src/registration_utils.cpp
src/thread_dispatcher.cpp

When sending a request with PJUtils::send_request, the callback may be called on the main PJSIP transport thread (which happens if there is a transport error when trying to send the request).
Since the callback is specified by the sender, it may involve lots of work that we don't want done on the main thread e.g. when we send a register to an AS (if the register fails and the iFC has session terminate, then we deregister the user which is a blocking HTTP request to homestead).
So we want to push these callbacks onto the worker threads instead.
We do this by:
* Creating a `Callback` abstract class that represents a callback that we want to run on the worker threads (and must hold all the data it needs)
* implementing a `RegisterCallback` concrete subclass that we use for registers to an AS …

[Reviewer: Richard] Perform PJUtils::send_request callbacks on a worker thread

---

include/uri_classifier.h
src/uri_classifier.cpp
src/ut/uriclassifier_test.cpp

This PR improves our URI classification to fix Metaswitch/clearwater-issues#1470.
There was a bug in the code that meant that if we didn't have enforce user=phone, and didn't enforce global only lookups, then we would always do an enum lookup on a URI, even if it was clearly not a phone number.
This PR improves our checking of the user part of SIP URIs to make sure that we actually have a phone number before classifying the URI as one. Please can you review.

[Reviewer: EM] URI classification

---

include/uri_classifier.h

Recent changes to `uri_classifier` broke the Houdini build, due to a missing include.  The sprout build wasn't broken, so presumably `string` got included elsewhere when building sprout.
@sathiyan-sivathas - FYI

Fix missing include

---

include/sproutlet.h
include/sproutletproxy.h
src/sproutletproxy.cpp

...because another sproutlet needs the method available on this interface.

[Reviewer: AJH] Add is_uri_reflexive to SproutletHelper

---

include/pjutils.h
src/pjutils.cpp

Self-explanatory. 
(Some of us like to scatter out sproutlet code with `const` at every opportunity.  I ran into this method when it stopped me from doing so.)

[Reviewer: Richard] Getting orig-served-user is a read-only operation

---

src/basicproxy.cpp

Mark the UAC as ready for deletion when a client is unresponsive. This fixes a issue I saw where the the UTs would leak memory when run with JUSTTEST="SCSCFTest*".
I've also removed the coverage exclusion statements since this code has clearly been covered since it caused a leak.

[Reviewer: AJH] Fix leaked UACTsx

---

include/constants.h

Add the pj_str_t constants required for MMF, separate to the current PR #1853

[Reviewer=HJS] Add MMF pj_str_t  constants

---

src/mmfservice.cpp
src/mmftargets.cpp
src/ut/mmfservice_test.cpp
src/ut/test_mmf_empty_name.json
src/ut/test_mmf_tab_name.json
src/ut/test_mmf_whitespace_name.json

The fixes following ST of the new mmf_targets.json file.  They include:
- Amend the previous ERROR trace printed with every invalid config, to better explain the behaviour
- Only allow A-Z, a-z, 0-9, -, and _ characters in the 'name' field.  The value of this field is sent as the 'mmfcontext' URI parameter when requests are forwarded to the MMF server, so the characters allowed here must be restricted
- Fix up some STATUS and DEBUG logs

[Reviewer=HJS] Fix following ST of mmf_targets JSON file

---

src/mangelwurzel/mangelwurzel.cpp

Currently we only initialise `_unmodified_request` for initial requests, which causes carnage on in-dialog requests when we try and use `_unmodified_request` in processing the response.
@GAB-MS

[Reviewer: Graeme] Save off original request for in-dialog transactions too

---

Makefile

This means that plugins-deb-only won't get called before plugins-deb when performing make deb.
This only works with `make -j 1` (as we need to guarantee dependency ordering), but the full fix requires rotating our make file targets to ensure Debian build targets correctly depend on their dependencies.

[Reviewer: Alex] plugins-deb prior to deb-only

---

sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_enum_json
sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_scscf_json
sprout-bgcf.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_bgcf_json

I added lines to make the following commands require sudo:
cw-upload_scscf_json
cw-upload_bgcf_json
cw-upload_enum_json
I've live tested these changes, and confirmed you now need sudo to run these commands

make upload scripts need sudo

---

include/sproutsasevent.h
src/scscfsproutlet.cpp

It was spotted the S-CSCF didn't raise SAS logs detailing when it was invoking MMF.  This PR adds these.
- SAS logs are only raised if MMF is being invoked - if MMF is switched off, then no logs are raised
- We raise separate SAS logs for pre-as and post-as MMF;  to combine these into a single SAS MMF log would require extra code, and wouldn't fit in as nicely to the current shape/ structure
- I am not sure of the policy for picking Sprout SAS log number ranges.  If I should be leaving more of a gap, please shout and I'll be happy to change

[Reviewer=HJS, AJH]  Add SAS logs detailing when MMF is invoked

---

include/sprout_pd_definitions.h
include/sproutlet_options.h
src/hssconnection.cpp
src/icscfrouter.cpp
src/main.cpp
src/ut/fakehssconnection.cpp
src/ut/siptest.cpp

The CL_SPROUT_SESS_CONT_AS_COMM_FAILURE ENT log has a placeholder in the Cause section. This PR makes the ENT log consistent with the other application server ENT logs.
Note - our current ENT log infrastructure only allows text replacement in the description section, so we can't make the Cause section more useful yet.
I've also fixed up some rogue newlines in logs as I was here.

[Reviewer: Krista] Fix placeholder in ENT log.

---

src/Makefile
src/ut/icscfsproutlet_test.cpp
src/ut/sip_parser_test.cpp

Alex,
This validates that the I-CSCF can route messages with a * or a # in the To header. It requires in order to pass https://github.com/Metaswitch/pjsip-upstream/pull/66.

[Reviewer: Alex] Test we can route * and # in To headers

---

include/constants.h
include/mmftargets.h
include/scscfsproutlet.h
src/scscfsproutlet.cpp
src/ut/scscf_test.cpp

Update mmf_context to be called mmf_target, to reduce confusion between config files.
Also fixing up the calls to add_mmf_uri_parameters, to pass the correct parameters in in the correct order (previously context and scope were mixed up) see https://github.com/Metaswitch/houdini/issues/812

rename mmf_context to mmf_target

---

include/sprout_pd_definitions.h
src/pjutils.cpp

ENT logs are meant to be for events that affect a node, not for things that affect a call.
This ENT log happens on a per-call basis, so I'm removing it (as the error can be debugged by SAS or by the engineering logs).

[Reviewer: Sathiyan] Remove ENT log

---

include/sproutlet_options.h

As discussed, we think this is the right change.

[Reviewer: Ellie] Remove port from the default Sproutlet URIs

---

include/sprout_pd_definitions.h
sprout-base.root/usr/share/clearwater/infrastructure/alarms/sprout_alarms.json

The alarm and PD log now warn that call setup time may also be increased if an
AS with session continued default handling is uncontactable.
Tested live, and verified that the correct text is seen

[Reviewer: Mat] Tweak AS comm failure text

---

src/as_communication_tracker.cpp

This is a fix for https://github.com/Metaswitch/clearwater-issues/issues/2293
As per the issue, we think the behaviour here is sensible so we just want to make it more transparent. We already say that the alarm will take 5-10 minutes to clear (https://github.com/Metaswitch/sprout/blob/dev/sprout-base.root/usr/share/clearwater/infrastructure/alarms/sprout_alarms.json#L252), so this just adds a warning log whenever we check if the servers are healthy again and decide that they're not. We log the servers that aren't healthy, and when the next check will be.
We still don't clear the alarm on startup - we require at least 5 minutes to pass without errors. We could easily set the `_next_check_time` to 0 so that the very first successful communication with an AS triggers it to clear if you think …

[Reviewer: Mat] Better logging for AS comm error alarms

---

src/Makefile
src/ut/sprout_test.supp

Seb,
This adds a valgrind suppression (in the same fashion as we have for Homestead) for a valgrind warning we've seen on certain machines.
We don't have the exact scenario for this, but I'm happy that it's fairly safe to suppress it because:
- We only see it during UT
- It always happens when the UTs are exiting rather than during execution
Short term plan is to suppress it and keep investigating.

[Reviewer: Seb] Ignore libc double free during test exit

---

include/constants.h
src/notify_utils.cpp
src/ut/subscription_test.cpp

(Section 5.1 of RFC3680)[https://tools.ietf.org/html/rfc3680#section-5.1] states that parameters from the contact header of a binding should be included in the `unknown-param` elements in the reg state NOTIFY. This PR makes that the case. 
Tested in UT, and also live (by @johadalin).

Include contact parameters on NOTIFY bodies

---

include/hssconnection.h
src/authenticationsproutlet.cpp
src/hssconnection.cpp
src/ut/authentication_test.cpp

Alex, this PR puts the constructed S-CSCF URI on the HTTP request that triggers the MAR at homestead. The `server_name` is encoded as a query parameter in the GET request.
Homestead PR to follow.

[Reviewer: AJH] Pass constructed S-CSCF URI on MAR

---

include/subscriber_data_manager.h
src/subscriber_data_manager.cpp
src/subscriptionsproutlet.cpp
src/ut/subscription_test.cpp

- Track the latest CSeq on a SUBSCRIBE received for each subscription.
- Only send NOTIFYs if the bindings have changed, the CSeq has changed or this is a new subscription.

Fix extraneous NOTIFYs being sent to other subscribers when a subscriber re-SUBSCRIBEs.

---

include/authenticationsproutlet.h
include/registrarsproutlet.h
include/sproutlet.h
src/authenticationsproutlet.cpp
src/bgcfsproutlet.cpp
src/icscfsproutlet.cpp
src/registrarsproutlet.cpp
src/scscfsproutlet.cpp
src/ut/sproutletproxy_test.cpp

Currently, the Sproutlet class has a method `aliases()` that just returns an empty list. This doesn't make any sense because every time a Sproutlet wants to use an alias it needs to override the `aliases()` method, and create its own `_aliases` member variable. It would be better to pass aliases into the Sproutlet constructor because it would remove duplicated code, and make it much easier to add an alias to an existing Sproutlet.

[Reviewer: AJH] Move aliases into sproutlet class

---

include/icscfsproutlet.h
src/icscfsproutlet.cpp
src/ut/coverage-not-yet
src/ut/icscfsproutlet_test.cpp

This PR takes the icscfsproutlet code to 100% code coverage, and removes it from the coverage exclusion list.
I've added tests for wildcards and S-CSCF selection failure when retrying a non-register request.
I've removed the on_cancel method when processing REGISTER requests, as this won't ever be hit.
I've excluded from coverage branches that are only hit when pjsip is unable to construct a URI, or methods to deal with in dialog requests.
Tested by running make full_test

[Reviewer: Ying] Improve the icscfsproutlet coverage to 100%

---

src/scscfplugin.cpp
src/scscfsproutlet.cpp
src/ut/scscf_test.cpp

Changes to the MMF URI's now that we no longer wish to route to MMF using the BGCF port
- For pre-as, use the mmf prefix
- For post-as, use the mmf service parameter (as we need to specify the exact node to route back to)
This also removes the now redundant `namespace` parameter.
NB:  This is likely a short-term fix, overridden by future changes following further high level thinking

[Reviewer: HJS]  Change MMF URI's

---

src/main.cpp

This removes the code from Sprout that's moved to cpp-common under Metaswitch/cpp-common#662

[Reviewer: Seb] Move duplicated code to cpp-common

---

src/basicproxy.cpp
src/ut/bono_test.cpp
src/ut/scscf_test.cpp
src/ut/testingcommon.h

I previously did some work reworking the sprout UTs - pull request #1890 
As part of this I accidentally cut out the code where the "Route" header was set in the scscf tests.
I've added this back in now.
I've also done minor tidying up around the codebase.
"make full_test" still passes.

Add route headers to sprout tests

---

include/aor.h

Reverting a commented out `private:` i left in, and the added `AoRPair` friend class line, which we don't need.

[No reviewer] Minor markups

---

include/aor.h

In https://github.com/Metaswitch/sprout/pull/1907 i un-commented something i'd missed, making the `_bindings` and `_subscriptions` private again. I ran make test, and all was good, so commited and merged. 
`make_test` doesn't respect privacy (rude), so they ran fine, but an actual `make` fails miserably, so i'm reverting the reversion here.

[No reviewer] make_test ignores privacy, so i checked in a bad fix

---

include/astaire_impistore.h
include/impistore.h
src/Makefile
src/astaire_impistore.cpp
src/authenticationsproutlet.cpp
src/handlers.cpp
src/impistore.cpp
src/main.cpp
src/ut/astaire_impistore_test.cpp
src/ut/authentication_test.cpp
src/ut/chronoshandlers_test.cpp
src/ut/handlers_test.cpp
src/ut/handlers_test.h
src/ut/mock_impi_store.h

This PR refactors the ImpiStore slightly:
* the old `ImpiStore` implementation is now an `AstaireImpiStore`, as its implementation is specific to Astaire
* the `AuthChallenge` objects are common to all possible store implementations, so remain in the `ImpiStore` rather than the `AstaireImpiStore`
* the `Impi` objects are now store-specific, so there's an `AstaireImpiStore::Impi`
* the `AuthChallenge` member variables are now private, so that Sprout must use the getters/setters to access them
`make full_test` passes, and the live tests pass

[Reviewer: Adam] Impistore refactor

---

include/astaire_impistore.h
include/impistore.h
src/astaire_impistore.cpp
src/impistore.cpp

A couple of further changes to the ImpiStore interface here.
1) A general `Impi` object no longer necessarily needs to be able to write itself as a JSON object, so that is now moved down from the `ImpiStore::Impi` to the `AstaireImpiStore::Impi`
2) I had left a `TABLE_IMPI` variable in the `ImpiStore`, which is actually an Astaire thing (It's still present in the `AstaireImpiStore`)

[Reviewer: Adam] Further impistore changes

---

src/ut/chronoshandlers_test.cpp
src/ut/handlers_test.cpp
src/ut/handlers_test.h

This is a follow-on from my PR #1905 
Just tweaks the UTs to use a MockImpiStore where appropriate
`make full_test` passes

[Reviewer: Adam] Fix up handler UTs to use MockImpiStore

---

include/aor.h
src/aor.cpp
src/ut/subscriber_data_manager_test.cpp

Mostly as discussed:
Functions added to AoRPair in aor.cpp to compare original and current AoRs in the pair, and return a list of updated/removed bindings/subscriptions.
I have left it with both sets of functions returning a full `Bindings` or `Subscriptions` map, so that these can be more generic, and potentially more useful in future. Can't see a reason not to do this, but you might have thoughts.
Otherwise `make` and `make full_test` both pass, so think all is good

[Reviewer: Richard] Utility functions in aor.cpp to find modified bindings and subscriptions

---

src/Makefile

Adam,
https://github.com/Metaswitch/cpp-common/commit/3f8f73d236d2bca0ce4a00d4fa786e2d684e0129 breaks Sprout because the test interposer files are built in a completely different way.
As far as I can tell, this is for no particular reason. I've run `make full_test` and verified everything is still good, so I can't see why we shouldn't just remove this.
The only relevant comment I can find is https://github.com/Metaswitch/sprout/blob/e6f127cbe8883cc0704601f22cb90091cba67e10/src/sprout_test.mk#L162-L168 - but I don't think that's actually required now.

[Reviewer: Adam] Build the interposer in the same way as other test files

---

include/impistore.h
src/impistore.cpp

As discussed, we want the ImpiStore to be able to store the expiry time in ms or s.
This adds that, defaulting to the usual seconds.
`make full_test` passes

[Reviewer: Richard] Allow impistore to store expiry in ms or s

---

src/astaire_aor_store.cpp

Stops the code crashing out if we receive an invalid non-object back from the store. We should definitely have been assuring that the doc was an object before attempting to perform an object specific action on it.

[No reviewer] Check doc is actually a JSON object before parsing

---

src/authenticationsproutlet.cpp
src/subscriber_data_manager.cpp

Avoid crashes when we haven't got a valid chronos_connection.
`make full_test` still passes fine

[No reviewer] Only use chronos connection if it exists

---

include/astaire_impistore.h
include/impistore.h
src/astaire_impistore.cpp
src/handlers.cpp
src/impistore.cpp
src/ut/chronoshandlers_test.cpp
src/ut/handlers_test.cpp
src/ut/mock_impi_store.h

This commit adds a boolean to the ImpiStore's `get_impi` method which allows it to include expired challenges. This is passed through to the `from_json` method so that the AuthChallenge will be included even if it's expired when this is set to `true`.
The AstaireImpiStore doesn't use this, to keep the behaviour the same for that.
`make full_test` passes.

[Reviewer: Richard] Allow ImpiStore to optionally return expired challenges

---

src/registration_utils.cpp
src/ut/registrar_test.cpp
src/ut/scscf_test.cpp
src/ut/siptest.cpp
src/ut/siptest.hpp

Hi Richard
Here's the Sprout PR companion to https://github.com/Metaswitch/pjsip-upstream/pull/68. Note that in addition to extending the UTs to check that bodyparts are as expected, I've added a verbose log of the 3rd party REGISTER (much as we have for sproutet-sproutlet traffic) so that you can see what it is in UTs (when you don't have the benefit of SAS).
Cheers
Steve

[Reviewer RJW2] Ensure content type appears once in bodyparts

---

include/cfgoptions.h
include/hssconnection.h
sprout-base.root/etc/init.d/sprout
src/hssconnection.cpp
src/main.cpp
src/ut/fakehssconnection.cpp
src/ut/hssconnection_test.cpp
src/ut/mock_hss_connection.h

This change is to accompany https://github.com/Metaswitch/homestead/pull/475
We expect that initial registers will take over 500ms in a GR deployment, so we need to increase the timeout Sprout specifies on its requests to Homestead. It defaulted to 500ms before, but this increases it to 750ms.
(All the other options in the constructor are the defaults from https://github.com/Metaswitch/cpp-common/blob/master/include/httpconnection.h#L31)
`make full_test` and the live tests pass.

[Reviewer: Richard] Increase Sprout's timeout to Homestead to 750ms

---

include/aschain.h
src/aschain.cpp
src/scscfsproutlet.cpp
src/ut/aschain_test.cpp
src/ut/scscf_test.cpp

This PR is a fix for https://github.com/Metaswitch/clearwater-issues/issues/2418
There's lots of detail in the issue, but in summary:
A change was made recently to allow Sprout to calculate the S-CSCF URI based on the route header that routed the request to Sprout, as that's usually what we want to do. However, when Sprout routes a request via an AS, the route header that routes the request back to Sprout will have Sprout's IP address in it, so the ScscfSproutlet was setting the S-CSCF URI to its IP address. It then sends this to Homestead, which may send it to the HSS on an SAR, which is bad.
This fix is to store the S-CSCF URI on the AsChain when we first create it. Then, when we get the request back from the AS, we correlate that transaction to the AsChain and retrieve the S-CSCF URI …

[Reviewer: Adam] Scscf uri on as chain

---

sprout-base.root/usr/share/clearwater/bin/poll_sprout_sip.sh

Project Clearwater BGCF is always installed on Sprout nodes, so we should be able to assume that it's running unless configured not to run.

[Reviewer: HJS] Add BGCF polling to poll_sprout_sip

---

include/aor.h
src/aor.cpp
src/handlers.cpp
src/registrarsproutlet.cpp
src/subscriptionsproutlet.cpp

Don't just copy the subscriptions and bindings if you're populating a new AoR.

[No reviewer] Copy all relevant fields from the AoR

---

sprout-base.root/etc/init.d/sprout

As discussed, this is a fix for https://github.com/Metaswitch/clearwater-issues/issues/2444
Homestead's latency on requests may be much higher that we had thought, because creating a new memcached connection will require an extra round trip. Across sites, the latency starts building massively.
We think this is the correct change for now

[Reviewer: Richard] Increase Sprout's default timeout for Homestead connections

---

include/constants.h
include/pjutils.h
src/common_sip_processing.cpp
src/pjutils.cpp

Idea is to correlate related SIP MESSAGE flows together so they show in SAS as a single trail group (search result). (Fix is limited in scope to SIP MESSAGEs.)
Alex - feel free to assign to someone else, just picked you because of your timely help on the RTR/PPR issue. :-)

Log Call-IDs from In-Reply-To headers as markers to SAS

---

src/Makefile

Use the new feature of the makefile in https://github.com/Metaswitch/clearwater-build-infra/pull/70 to exlcude all the Bono tests unless the variable `SLOW` is set. This allows us to speed up the valgrind check for most use-cases. I'm expecting that most developers will want to run without SLOW set, but that our automated builds will run with it set.
So, to run valgrind over everything, you now run
`SLOW=T make valgrind_check`
like we have in etcd.
An example of the speed-up I saw (on the repo server, so not one where we have to drastic slowdown that we've seen in some cases):
```
time make valgrind_check
...
real    4m2.077s
user    3m53.094s
sys     0m1.847s
```
vs
```
time SLOW=T make valgrind_check
...
real    5m50.543s
user    5m41.626s
sys     0m1.866s
```
That's a 2-minute saving …

[Reviewer: Adam] Use target-specific exclusions

---

src/stack.cpp

Krista, please could you review this change to sprout to make it log the thread ID of the transport thread. This allows you to monitor the thread's CPU usage using tools like [htop](http://hisham.hm/htop/). 
With this change, `/var/log/sprout/*` contains the following log:
```
05-10-2017 10:01:16.629 UTC Status stack.cpp:150: PJSIP transport thread started with kernel thread ID 24384
```

Have the transport thread log out the thread ID assigned by the kernel

---

src/main.cpp

Makes it clearer that we're aborting startup because of failures setting up plugins or stores.

Better startup logging

---

src/astaire_aor_store.cpp

Updates us to use the same macro as we use in the impistore. e.g. https://github.com/Metaswitch/sprout/blob/dev/src/impistore.cpp#L138 
Just makes it a bit clearer to read. Tested and all works fine.

[No reviewer] Make code cleaner, using JSON macro

---

include/cfgoptions.h
include/sproutsasevent.h
include/thread_dispatcher.h
sprout-base.root/etc/init.d/sprout
src/main.cpp
src/thread_dispatcher.cpp

This PR ages out old requests if they've been on the queue for too long; rejecting them in the same way that we reject on overload.
It's not been tested, and I've not thought about what a sensible default would be.

[Reviewer: Tom] Reject on queue

---

sprout-base.root/etc/init.d/sprout

Adam,
Hopefully an uncontroversial change to add a couple of configuration options for the thread counts to Sprout.
I've tested setting `sprout_worker_threads` and `sprout_http_threads` on a Chef deployment and checking that they get picked up.

[Reviewer: Adam] Add sprout_{http/worker}_threads to override num_*

---

src/Makefile

Currently `make full_test` doesn't work on a clean checkout because it fails with:
```
g++   -MMD -MP -O0 -ggdb3 -std=c++11 -Wall -Werror -DUNIT_TEST -fprofile-arcs -ftest-coverage -fno-access-control -I../modules/gmock/gtest/include -I../modules/gmock/include -I../modules/cpp-common/test_utils -Wno-write-strings -I../include -I../modules/cpp-common/include -I../modules/app-servers/include -I../usr/include -I../modules/rapidjson/include `PKG_CONFIG_PATH=../usr/lib/pkgconfig pkg-config --cflags libpjproject` -I../modules/sipp -I../modules/app-servers/test -I../modules/memento-as/include -I../modules/memento-as/modules/memento-common/include -I../modules/gemini/include -I../include/mangelwurzel -Iut -DGTEST_USE_OWN_TR1_TUPLE=0  -c ut/hssconnection_test.cpp -o …
```

[Reviewer: Seb] Depend correctly on the alarm definition file

---

include/chronoshandlers.h
src/chronoshandlers.cpp

Mat,
Currently Chronos processes work for a AoRTimeout immediately after it calls `send_http_reply(HTTP_OK);` to reply to the HTTP request, in the same function call.
However, the HTTP server stack, libevhtp, doesn't process the reply until the thread returns to it's control. This means that the reply isn't sent until the function returns, which in the case of an AoRTimeout when we need to potentially send a request to the HSS and perform work in a different GR site may be hundreds of ms later.
This means that we can see double pops of timers, as Chronos doesn't get a response in time, and thus the timer pops multiple times.
This fixes it by moving the work to the Sprout worker thread pool, using our common PJUtils code to do so.
I've tested that the UTs pass, and the live tests pass, …

[Reviewer: Mat] Run AoR Timeout Task on worker pool

---

include/subscriptionsproutlet.h
src/subscriptionsproutlet.cpp
src/ut/subscription_test.cpp

There were a couple of issues present in the old code for creating/updating subscriptions:
* We would perform multiple remote reads on a new subscription 
* If we were unable to create a subscription (because we couldn't read a contact header), we would still update associated IMPUs in the respective AoR, and respond with a 200 OK if the store was updated.
These changes do the following:
* Perform an early check on the contact header, before even reading to the HSS to check registration state, and reject the subscription with a 400 Bad Request if we fail to parse it. This is unlikely to happen, but will save us a bunch of time if we do hit that condition.
* Refactors the old `write_subscriptions_to_store` into a number of new, clearer functions. The flow is now as follows:
* We create a …

[Reviewer: Richard] Subscription sproutlet refactor

---

include/basicproxy.h
src/basicproxy.cpp
src/ut/basicproxy_test.cpp

This PR fixes a bug in graylisting where a host would get blacklisted whenever it gets sent an ACK. 
The problem was that the `Target` class white/blacklists the host automatically if it hasn't been told the state of the host by the time the `Target` gets destroyed or unset (e.g. because we're moving onto another target). This caused a problem for ACKs since the only way we know a host is definitely healthy is receiving a response from it, and ACKs don't have responses. 
I've fixed this by having the `UACTsx` tell the `Target` whether the host should be blacklisted by default. This flag is only set for requests that have a PJSIP transaction (meaning they require a response), and the host is not a stateless proxy. 
Tested in UT. ST will follow when I've merged this PR to the integration …

Fix graylisting ACK bug.

---

src/sipresolver.cpp
src/ut/sipresolver_test.cpp

Companion PR to https://github.com/Metaswitch/cpp-common/pull/699. This copes with the host state logic being moved into the base resolver, and also updates the UTs.

Move IP address allowed host state checking to the base resolver

---

src/notify_utils.cpp
src/ut/subscriber_data_manager_test.cpp

Hey Ellie it seemed strange that this code for DEACTIVATED is uncovered and a bug seemed very likely. It so happens that all Admin Dereg cases in handler_test are using Mock SDM, and only one subscriber_data_manager_test uses Admin Dereg.
This one test that should cover the code didn't have associated_uri set before. Now it does and goes through the right function calls. 
`make full_test` passed.

Hit uncovered code for Admin Dereg

---

src/impistore.cpp

Improved log as part of investigating https://github.com/Metaswitch/clearwater-issues/issues/2110.   When the JSON gets large, the log gets truncated and previously that meant that you lost the error code.

Improve error logging on JSON parse failure

---

sprout-base.root/etc/init.d/sprout

Default to 250 sprout worker threads per core, because the threads are blocking.
I've live tested that this defaults correctly, and we've already live tested that this number of threads fixes the latency issues.

[Reviewer: Adam] 250 worker threads per core

---

src/enumservice.cpp
src/registrarsproutlet.cpp
src/registration_utils.cpp

Seb,
I've tweaked a couple of log levels. In all cases, the event will be being SAS logged anyway, and these are per call events, so we shouldn't really have engineering logs for them at Warning level.
There's more detail in the commits themselves.

[Reviewer: Seb] Tweak log levels to prevent log spam in expected cases

---

debian/sprout-scscf.links

This reorders links to put a gap between sbin and bin, also makes the remove scripts require sudo

Updates sbin and divides sbin and bin scripts

---

src/main.cpp
src/thread_dispatcher.cpp
src/ut/thread_dispatcher_test.cpp

Two small changes to sprout's overload behavior:
* Now that the latency calculation doesn't include downstream latency, the default target latency should be reduced. I've run a sprout node under rated load and the smoothed latency was typically ~2000us, so setting the default to 10000us seems reasonable. 
* We've agreed to ignore the load monitor on all SUBSCRIBEs, not just dialog creating ones. The argument here is SUBSCRIBEs are really just follow on work from having accepted the REGISTER.

Tidy up overload code

---

src/main.cpp
src/sproutletproxy.cpp

Seb,
If a timer pops, and before being scheduled, it's cancelled, it'll still be executed.
This protects against this by checking whether it's still one of the pending timers.
We also attempt to avoid a race condition by changing the TCP connect timeout away from matching the 2 seconds we have as a value for the AS Session Continued timeout.
Doing this, running stress across a deployment with a failed app server, and running the live tests, I don't see any failures.

[Reviewer: Seb] Fix and avoid race condition in Sproutlet timers

---

src/registrarsproutlet.cpp
src/registration_utils.cpp
src/subscriber_data_manager.cpp

As discussed, in debugging some SUBSCRIBE / NOTIFY flows, I've wanted additional trace in the code.
I've added the following, all of it at INFO or DEBUG level.

[Reviewer: Ellie] Add additional trace for registrar and SDM flows

---

src/thread_dispatcher.cpp

Alex,
This resolves two problems involved running at load with latency:
- It's very difficult to work out what is responsible for causing overload to kick in, because we don't have anything logging long requests. I've added some logs, which based on some runs I've done, I've logged requests which take 50 times are target latency. Testing showed that 10 times was too little.
- We don't correctly assign the stopwatch to the IO Hook, which negates it's purpose.
I've tested this live, and it resolves these two problems

[Reviewer: Alex] Resolve problems running at load with latency

---

debian/sprout-base.postinst

We can achieve the same thing using ulimits, and setting the capability breaks advanced backtraces.

Remove the "nice" capability from the sprout executables

---

src/thread_dispatcher.cpp
src/ut/thread_dispatcher_test.cpp

Ignores load monitor for:
- Requests containing an ODI token.
- all registrations.
- MESSAGEs with "urn:service:sos" in the request URI.
SAS PR to follow.

[Reviewer: EM] Ignore load monitor for emergency requests and AS requests

---

sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/config_validation/rph_validation.py

I've edited the rph.json validation to:
- be case insensitive when parsing rph headers (Metaswitch/clearwater-issues#2803)
- allow higher priority headers to be the _same_ priority as lower priority headers (although they still can't be lower priority (Metaswitch/clearwater-issues#2804)
I've live tested this:
With file:
```
{
"priority_blocks":
[
{
"priority": 1,
"rph_values": ["eTs.0", "ets.0"]
},
{
"priority": 2,
"rph_values": ["EtS.0"]
}
]
}
```
I got the error message below when I attempted to validate it:
```
ubuntu@ip-10-0-119-195:~/codebase/sprout/sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/config_validation$ python rph_validation.py rph_schema.json rph.json
rph.json is not valid.
The errors are printed below:
ets.0 is present more than once.
ets.0 is …
```

Correct minor rph.json validation issues

---

include/rphservice.h
src/rphservice.cpp
src/ut/rphservice_test.cpp
src/ut/test_badly_ordered_rph.json
src/ut/test_duplicated_value_rph.json
src/ut/test_rph.json

Adds a case insensitive key_compare function for the RPH map so that an RPH value with different case to the one configured still returns the correct priority.
Tested by changing the cases of random characters in RPH values in the UTs. I did this in the config files to check that config validation still works, and in the tests to check key lookups work with different cases.

[Reviewer: KH1] Add case insensitive compare function to RPH map

---

src/stack.cpp

Hi Matt
Would you mind reviewing this small fix for me?  I'm hoping it will fix Rob's crash in https://github.com/Metaswitch/clearwater-issues/issues/1441, which is a critical problem for the upcoming release, so would like to get it in tomorrow if possible.
As we don't seem to be able to repro Rob's scenario, I've tested it by hacking into PJSIP a high severity PJ_LOG call with a parameter containing '%' characters (which I believe is the root cause of Rob's crash).  Without this fix, that gets corrupted in the output - with the fix, the logged string appears as expected.

[Reviewer MIRW] Handle % characters correctly in PJ_LOGs

---

include/registrarsproutlet.h
src/registrarsproutlet.cpp
src/subscriptionsproutlet.cpp

The CSeq counter for a SUBSCRIBE/NOTIFY dialog is stored on the AoR corresponding to that dialog, and this AoR is stored in memcached both locally and at remote sites. Any time the local SDM increments the CSeq it relies on the client also calling into the remote SDMs to increment the CSeqs on the remote copies of the AoR. Whenever a NOTIFY is sent from the local site, it uses the local CSeq value and increments both the remote and local values, and similarly when a NOTIFY is sent from the local site. 
Due to a netsplit or perhaps another unknown condition (edit: while testing this, I ran into two other existing bugs that consistently cause out-of-sync CSeqs - I think it's only luck that we don't hit them more frequently), the counters can become out of sync between the local and remote …

[Reviewer: SS5] Recover from CSeq desync

---

src/subscriber_data_manager.cpp
src/ut/registrar_test.cpp

Hi Ellie
Can you review this "terminate and recreate Contact in NOTIFY if Contact URI changes" fix?  I think the customer is going to want it in 11.1 - can we get it in despite the code freeze?
Some notes
- I tested live using sipp scripts to sending in a UDP REGISTER to a given IMPU first from one client box and then from another.  I confirmed that the P-CSCF was apparently happy to delete the old contact
- I haven't changed the logic for analytics, which means that (I think), we'll get both a call to
_analytics->registration(classified_binding->_b->_address_of_record,
classified_binding->_id,
classified_binding->_b->_uri,
0);
and to 
_analytics->registration(classified_binding->_b->_address_of_record,
classified_binding->_id,
classified_binding->_b->_uri, …

[Reviewer EM] Send out terminate+create contact in NOTIFY if Contact URI changes

---

include/pjutils.h
src/pjutils.cpp
src/ut/fakehssconnection.cpp
src/ut/fakehssconnection.hpp
src/ut/registrar_test.cpp
src/ut/sip_parser_test.cpp

Hi Richard
Are you OK to review this change for me (we discussed last week - its the fact that we don't quote "gen-values" of Charging function params in PCFA headers, contrary to the BNF in RFCs 3588 and 3261)? It would be good if you could find time to do this this week as the MMF workaround we gave to the customer might not work (as it would need to differentiate between ';' chars that are part of the values and not ccf/ecf parm separators).
I've taken care to quote only values that contain non-host/token characters (making the assumption that any value that starts with '[' is an IPv6 address and therefore doesn't need quoting, as is made elsewhere in sip_parser).
Note that I had to add a _hss_connection->set_impu_result to TEST_F(RegistrarTest, SimpleMainlinePassthrough), rather than …

[Reviewer RJW2] Quote pcfa params

---

src/basicproxy.cpp

This fixes up the log that you were seeing in your stress runs. Tested by running the UTs.

Make a log that can be hit on each call INFO level

---

src/subscriber_data_manager.cpp
src/subscriptionsproutlet.cpp

Fixes some issues with [#2029](https://github.com/Metaswitch/sprout/pull/2029). Namely:
- The CSeq is correctly updated when we hit data contention writing to the local store;
- The spammy log has been removed;
- The CSeq counter is more resilient to read/write race conditions.
I've tested these changes as follows.
Recovery can be slow if there is a large discrepancy in CSeqs, but after sufficiently many SUBSCRIBEs the counter _will_ recover, which is better than the current behavior.

Recover from CSeq desync (fix)

---

src/sproutletproxy.cpp
src/ut/sproutletproxy_test.cpp

Alex, this PR provides a fix for a scenario where we could crash in the Sproutlet Proxy if we receive a certain type of SIP message. The conditions required for the crash are:
- We receive a SIP message with no route header and a Tel URI in the request line.
- A Sproutlet is matched using a port since there is no SIP URI to match on (and Sproutlets can't be matched on Tel URIs).
- The Sproutlet is uninterested and forwards it onto another sproutlet by calling `get_routing_uri()`.
Before this fix,  `get_routing_uri()` would return the Tel URI in the request line and cast to a SIP URI which would cause a crash. The fix is to fall back to `_root_uri` in the cases where `get_routing_uri()` would return a Tel URI. Tested in UT by writing a test that crashes/passes before/after my fix and …

[Reviewer: AJH] Make sure get_routing_uri returns a SIP URI

---

src/contact_filtering.cpp
src/ut/contact_filtering_test.cpp

What the title says. From an internal Metaswitch issue:
> When a Polycom VVX300 (and possibly other Polycom phones) registers, it signals RFC3840 feature
> support in the Contact header, by sending a Contact of the form:
> 
> Contact: <sip:5932224461@10.248.255.248:5060>;methods="INVITE, ACK, BYE, CANCEL, OPTIONS, INFO, MESSAGE, SUBSCRIBE, NOTIFY, PRACK, UPDATE, REFER"
> 
> ...
> 
> This causes trouble in an IMS network, where Clearwater fails to match some types of method to the 
> supported methods list (on the grounds that, say, " NOTIFY" with the leading space isn't the same as 
> "NOTIFY" without the space), concludes that the Polycom doesn't support this method, and doesn't send 
> the message to that contact address (and, if the Polycom is the only registered contact address, the …

Trim whitespace when matching contact filtering tokens

---

src/ut/scscf_test.cpp
src/ut/siptest.cpp

This is the continuation of the fix to Metaswitch/clearwater-issues#2825.
I have fixed up 32 tests, which were broken by correcting the `expect_target()` function.
(This function was changed in PR #2046.)
These were all incorrect for the same reason (the final destination was expected as bono, not the callee).
This fix can be checked in now, as `make full_test` passes with this fix in place.

Fix up incorrect UTs in sprout

---

Makefile

Not urgent, but a nice build improvement.
Currently plugins get built twice by Sprout.
The model is:
- `deb` builds the target and the Debian package
- `deb-only` just packages the plugin
Thus when calling Sprout `deb` we need to build the plugin, and call `deb-only`,
not build, `deb` and `deb-only`.
Currently,
- `build` calls `plugin-build` which calls `make` in a plugin (which builds the plugin).
- `plugins-deb` calls `deb` in the plugin which builds the package
- `deb-only` calls `plugins-deb-only` calls `deb-only` in the plugin, which rebuilds the package (sigh).
Given that we are calling build, the right fix, I think, is to not call `plugins-deb` when calling `deb` as it'll have been done by either a combination of a) `build` and b) `deb-only`.

[Reviewer: Huw] Don't call deb and deb-only on plugins

---

src/uri_classifier.cpp
src/ut/common_sip_processing_test.cpp
src/ut/testingcommon.cpp

Hi Alex, would you mind reviewing this fix?
This is a simple fix to URI classifier. Sprout classified local node URIs, such as those used for Options polls, incorrectly when the "user=phone" URI parameter was spuriously specified. 
I have also had to modify the UT framework a bit by allowing to send requests containing no user part in the SIP URI (so that the '@' sign is not included).
I have written a new UT to test my changes and all UTs passed, as well as run a live test on our L3 test system (running v11.0.2).

[Reviewer: AJH] Options polling to Sprout with URI parameter "user=phone" included

---

debian/control

The AIO node doesn't currently install rogers - as it installs `ellis-node bono-node restund sprout-node homer-node homestead-node clearwater-prov-tools` (as per https://github.com/Metaswitch/clearwater-infrastructure/blob/master/scripts/clearwater-aio-install.sh#L48 ).
This updates sprout-node to reference `rogers`, which it should anyway, which fixes that.

[Reviewer: Seb] Update rogers dependency

---

include/sproutlet.h
include/sproutletproxy.h
src/authenticationsproutlet.cpp
src/compositesproutlet.cpp
src/registrarsproutlet.cpp
src/scscfsproutlet.cpp
src/sproutletproxy.cpp
src/subscriptionsproutlet.cpp
src/ut/registrar_test.cpp
src/ut/sproutletproxy_test.cpp

Alex,
This PR enhances `get_routing_uri()` to check that the URI it finds on a request is reflexive before returning it as a routing URI. Please can you review. This addresses the scenario where a message can contain a non-local SIP URI that we then use to route between Sproutlets which will fail.
I've had to change the Sproutlet API slightly with this change but the impacts are quite small. I've added UTs to get full coverage in this area of code.
Thanks,
Sathiyan

[Reviewer: AJH] Check URI is reflexive when getting routing URI

---

src/thread_dispatcher.cpp

Noticed a couple of errors in log lines that I think you added:
1) typo in "Received"
2) both these logs erroneously claimed to be on a worker thread, when they're actually on the transport thread. Since we log the thread id anyway, I figured we may as well just remove that part of the log.

[Reviewer: Tom] Fix up incorrect log lines

---

include/handlers.h
src/handlers.cpp
src/main.cpp
src/registration_utils.cpp
src/ut/chronoshandlers_test.cpp

This PR makes AoRTimeoutTask sends third party REGISTER when all bindings have expired, similar to DeregistrationTask and DeleteImpuTask and consistent with TS24.229.
1. The task calls deregister_with_application_server after updating hss, similar to RegistrationUtils::remove_bindings. Spec p.235-238 suggests that ordering as well.
2. AoRTimeoutTask now gets fifc_service and ifc_configuration in its Config, for the use of deregister_with_application_server.
2. UT checks deregister_with_application_server is called by log, which isn't ideal. Unfortunately deregister_with_application_server is an utility function and does not return success or not (I feel it should), so handler_test is checking this call by log as well.
full_test passed

Deregister AS in AoR Timeout Task

---

src/custom_headers.cpp
src/ut/sip_parser_test.cpp

Picking you because I think you've done a chunk of Sprout UT work recently and I think the UT changes are the most interesting part of this PR - if I've misremembered or you have too much on your plate, let me know.
L3 raised on Slack (I don't think there's an issue yet) that our Accept-Contact header parsing doesn't accept comma-separated values - `Accept-Contact: *;foo,*;bar` should be equivalent to:
```
Accept-Contact: *;foo
Accept-Contact: *;bar
```
but it fails to parse. Generally I'm a bit worried about this - I think we've hit a few header parsing bugs in our custom headers recently - so I've tried to figure out how to improve the testing here.
This PR:
* adds a specific test for comma-separated values, `AcceptContactMultiple`
* fixes up the Accept-Contact parser to make it work, …

[Reviewer: Krista] Accept-Contact fixes

---

src/authenticationsproutlet.cpp
src/registrarsproutlet.cpp
src/subscriptionsproutlet.cpp
src/thread_dispatcher.cpp

@rkd-msw please sanity check that these are sensible checks. I don't think there are other sproutlets we can hit this on.

Add extra logging for debugging 500 responses *not for dev branch*

---

src/pjutils.cpp

Seb,
If we send a SIP request to another SIP node using `PJUtils::send_request`, e.g. Third Party Registrations, if `pjsip_tsx_send_msg` fails, we can leak the `pjsip_tx_data`'s pool, which leaks a bunch of memory.
This is because we `pjsip_tsx_send_msg` will not decrement the reference count isn't decremented if pjsip_tsx_send_msg fails.
I've written further detail on exactly what semantics are of the memory management, and why this is the right thing to do inline. There's no current UTs for pjutils.
This is conceptually a follow on to https://github.com/Metaswitch/sprout/pull/2001
I've tested with a long low load, under massif, and I'm now running a longer stress test with a higher load to test this further.

[Reviewer: Seb] Don't leak PJSIP transactions sending SIP messages

---

include/pjutils.h
src/icscfsproutlet.cpp
src/pjutils.cpp
src/scscfsproutlet.cpp
src/ut/icscfsproutlet_test.cpp

Alex,
I think you are best placed to review this given we discussed the fix?
If we are invoking a server to handle a non REGISTER event, it's useful to log
the IMS Charging Identifier in the P-Charging-Vector as this allows us to link
up calls across B2BUAs via directly attached AS.
This should then correlate with the same marker raised by an S-CSCF when it receives a new request.
I haven't live tested this, but I have updated the UT to check the correct marker is raised.

[Reviewer: Alex] Log IMS Charging IDs to SAS from the I-CSCF

---

include/custom_headers.h
src/custom_headers.cpp
src/ut/sip_parser_test.cpp

Hi Rob,
This PR complements your Accept-Contact PR #2064. Consequently, I believe you are the best person to review this.
In this fix, I have:
- Fixed the Reject-Contact header parser to allow parsing of headers with multiple rc-values.
- Merged the routines for parsing Accept-Contact and Reject-Contact headers into one common routine.  I think this makes sense since the routines are virtually the same with only minor differences. having a common routine also reduces the possibility of an error when the parser get updated in the future.
- Added a UT for parsing Reject-Contact header with multiple rc-values. Note that by combining the two routines, the extensive UTs that you have added as part of your fix test the Reject-Contact code as well.
I have tested the fix by running make …

[Reviewer: RKD] Reject-Contact fixes

---

include/subscriber_manager.h
src/ut/mock_subscriber_manager.h

Adds the methods we discussed. A few assumptions:
- register_subscriber can't remove bindings since there's no stored AoR.
- register_subscriber can't result in a deregistration so no IRS info is returned.
- Only register_subscriber takes a server name since we should not change the stored server name on re-registrations.
Does that sound reasonable?

[Reviewer: EM] Update SM API

---

include/handlers.h

Moved TimerHandler into cpp-common during develpment of sdm-refactor, which isn't merged yet.

Remove TimerHandler

---

src/registrarsproutlet.cpp
src/ut/registrar_test.cpp

Hi Krista
Can you sign off on this fix for me?  The problem here is that, if a "fetch bindings" REGISTER (one with no Contact headers) is received for an IMPU that has ASes that need 3rd party registration, Sprout forwards the REGISTER to the AS with an expires value of 0 (because the incoming REGISTER didn't include an Expires), which results in, e.g., call drops because the AS thinks its being told to deregister the sub.  
My view is that we should suppress forwarding of 3rd party REGISTERs if the REGISTER is a "fetch bindings" REGISTER, because these REGISTERs are just querying the bindings - they aren't intended to change state - so there's no need to forward them to the AS.
Tested live and via the UT.  Note that I deliberately amended an existing UT (rather than write a new one).  My …

[Review KH1]: No 3rd part register for fetch binding

---

src/chronoshandlers.cpp
src/main.cpp
src/ut/subscriber_manager_test.cpp

Avoid using PJSIP callback in S4, by creating a Callback class. Not live-tested but full_test passed.
Together with https://github.com/Metaswitch/clearwater-s4/pull/21

Chronos threading

---

include/registration_sender.h
include/subscriber_manager.h
src/registration_sender.cpp
src/subscriber_manager.cpp
src/ut/registration_sender_test.cpp
src/ut/s4_test.cpp

Sathiyan, please can you review this change to split the SM callback interfaces into two classes (and some associated renaming)? 
Tested in UTs, which all pass (barring the valgrind errors I just messaged you about).

Split the SM callback interfaces into separate classes

---

include/cfgoptions.h
include/stack.h
sprout-base.root/etc/init.d/sprout
src/main.cpp
src/stack.cpp
src/ut/siptest.cpp

Hi Alex, could you please review this?
This PR removes the `max_session_expires` parameter from the sprout code (this is the only repo that references that parameter). The code that used the parameter was retired already in 2015 (see https://github.com/Metaswitch/sprout/commit/8666b17cc85c64b4b19bb629da86eec4774ccd1e#diff-ec6a7d93b16090d00cb1274ef494ac04).
I have tested the fix by patching a box and restarting sprout with the "max_session_expires" option set in shared_config. Doing "ps -ef | grep sprout" showed that the option wasn't picked up during startup. I also tried putting a test call through the system to see if everything works as it should.

[Reviewer: Alex] Retired max_session_expires parameter

---

include/subscriber_manager.h
src/subscriber_manager.cpp

Well that was easy (and I wasted a depressing amount of time failing to do something more complicated).
UTs pass. I can't easily test that the code is actually transferring to a new thread (since the PJUtils function detects when it is in Unit test and if it is, runs the callback on the current thread).

Process timer pop callbacks on the PJSIP worker threads

---

src/authenticationsproutlet.cpp
src/bono.cpp
src/impistore.cpp
src/sproutletproxy.cpp

Update to be in line with typo fix in the sas-client. PR [here](https://github.com/Metaswitch/sas-client/pull/82).
Typo in commit message is intentionally ironic.

[Reviewer: CJR] Fixed marker ID typo

---

src/Makefile
src/main.cpp

I need to make similar changes in:
I don't think it's valuable to add this functionality to:

[Reviewer: RND] Load records from /etc/clearwater/dns.json

---

include/scscfsproutlet.h
src/scscfsproutlet.cpp
src/ut/fakehssconnection.hpp
src/ut/scscf_test.cpp

If we aren't doing ENUM, and we have a URI which is already known to be
off-net, don't bother routing it to the I-CSCF which will need to perform an
LIR.

[Reviewer: Seb] Route off-net calls to the BGCF when not doing ENUM

---

include/pjutils.h
src/custom_headers.cpp
src/pjutils.cpp
src/ut/sip_parser_test.cpp

Hi Krista
Can you review this fix for me this week (before the code slush)? Its a fix to Sprint-critical issue https://github.com/Metaswitch/clearwater-issues/issues/3646.
Fix here is to refactor the PCFA print code (which has the same quoting requirement) and use this code to correctly quote the parameters for the PCV, with a couple of exceptions
-  I've left the icid-value as "always quote", for two reasons:  Its what the code explicitly did already (possibly for interworking reasons) and we want to cope with the "icid-value is zero-length" case (icid-value is mandatory in the PCV, and I expect 'icid-value=;....' to be rejected by the downstream node as unparseable, whereas 'icid-value="";...' is less likely to cause problems)
-  the icid-generated-at parameter only takes "host" …

[Reviewer Krista] Correctly quote PCV header contents

---

include/sproutletproxy.h
src/scscfsproutlet.cpp
src/sproutletproxy.cpp

Hi Richard
Are you OK to review this two-pronged timer cancel fix?  
No UTs, but I managed to test first the timer handling code in scscfsproutlet with this "slow DNS" repro scenario (which stopped the crash, but a random leg got CANCELled and the call failed) and then the "cancel timer even if popped" code in sproutletproxy with the same slow repro (this time the call completed fine, with the slow timer being properly cancelled) altogether.
I haven't been able to come up with a repro scenario for the "extra response" case in scscfsproutlet, but I'm going to claim that the backstop code is good by inspection (and "make full_test" passes).
I'll reference the associated SAS resource bundle fix shortly

[Reviewer RJW2] Ensure PJSIP timers that are cancelled after they've popped do not make it into the sproutlets

---

debian/control

Currently if you install mangelwurzel-as-dbg you don't automatically get sprout-base-dbg (which also includes sprout-libs-dbg and gdb) when you probably should. This fixes that by adding sprout-base-dbg as a recommended package for all of the sproutlet debug packages.

[Reviewer: GDR] Install sprout-base debug package for sproutlets

---

src/common_sip_processing.cpp

Turns out you were right, it wasn't that hard! Tested by building and deploying https://github.com/Metaswitch/sprout/commit/93c2babe56687bd4aea4bc7f2c49abd409740b6d, sending a REGISTER, and checking it came up in SAS when I searched for a SIP 503 but not when I searched for a SIP 423.

[Reviewer: RND] Allow searching for SIP errors in SAS 

---

debian/sprout-libs.install
docs/IOTraps.md
src/Makefile
src/thread_dispatcher.cpp

This PR builds an IO trap library that can be used to check if sprout worker threads are doing IO without first calling `CW_IO_*`. 
This PR is not quite complete as I haven't decided how to run this going forwards. There are two options:
* Run sprout from the command line, and explicitly load the IO trap as described in https://github.com/Metaswitch/cpp-common/pull/779. In this case all that's needed is some documentation. 
* Add a shared config option that can be used to automatically load the IO trap when sprout starts. That needs more code and I'm not quite sure how to do it yet. 
However I still think it's worth gettting the code reviewed as it stands. I'll do one of the above either as a separate commit or a separate PR.

Build IO trap library for sprout
