Metaswitch/sprout

- sprout/basicproxy.cpp
As discussed, if the TCP transport is really congested it's possible that the original send is still pending in the transport layer and thus the `tdata` is not (exclusively) owned by the transaction layer or the basic proxy layer.  In this case we simply clone the old `tdata` and replace it with it's own clone, dropping our reference (the transaction has it's own reference).  The transaction will eventually terminate at some point and clean up the abandoned `tdata`.
Tested live by @plfrancis to confirm that this fixes #919.
> Reviewer Matt - Create new tdata before re-try if TCP is super congested

- include/icscfsproutlet.h
- sprout/icscfplugin.cpp
- sprout/icscfsproutlet.cpp
- sprout/ut/icscfsproutlet_test.cpp
- sprout/ut/test_enum.json
Ellie,
Please can you review my enhancement to fix #927?  It should be reasonably self-explanatory.
I've UT-ed and live-tested.
Thanks,
Matt
> [Reviewer: Ellie] I-CSCF should route to BGCF when appropriate

- include/icscfsproutlet.h
- include/pluginloader.h
- include/scscfsproutlet.h
- include/sprout_pd_definitions.h
- include/sproutletplugin.h
- sprout/bgcfplugin.cpp
- sprout/cdivasplugin.cpp
- sprout/geminiasplugin.cpp
- sprout/icscfplugin.cpp
- sprout/icscfsproutlet.cpp
- sprout/main.cpp
- sprout/mangelwurzel/mangelwurzelplugin.cpp
- sprout/mementoasplugin.cpp
- sprout/mmtelasplugin.cpp
- sprout/pluginloader.cpp
- sprout/registrar.cpp
- sprout/scscfplugin.cpp
- sprout/scscfsproutlet.cpp
- sprout/ut/icscfsproutlet_test.cpp
- sprout/ut/scscf_test.cpp
Matt, can you please review this change to check whether a plugin has loaded correctly, and exiting if not. 
Testing by making the scscf-uri invalid, and checking that Sprout died
Fixes #935
> [Reviewer: Matt] Check whether the plugins load

- sprout/notify_utils.cpp
> Reviewer RKD: Fix invalid read

- sprout-base.root/etc/init.d/sprout
Conflicts:
sprout-base.root/etc/init.d/sprout
> Reviewer RKD: Scale HTTP threads according to number of CPUs

- sprout/regstore.cpp
Alex, can you review this change to add in the SAS trail when sending a put/post to Chronos
> [Reviewer: Alex] Log Chronos registrations

- debian/control
- mk/libmemcached.mk
Identical to the change in Ralf.
> [Reviewer: Ellie] Extra 14.04 stuff

- docs/Development.md
- include/cfgoptions.h
- include/sprout_pd_definitions.h
- sprout-base.root/etc/init.d/sprout
- sprout/main.cpp
Andy, can you review this change to update the interactive options. 
Fixes #851
> [Reviewer: Andy] Update interactive options

- debian/bono.init.d
- debian/clearwater-sip-stress-stats.init.d
- debian/control
- sprout/main.cpp
Andy,
Please can you review these changes to integrate Sprout with Astaire?  Note that the PIDILE -> PIDFILE corrections are just something I spotted while testing.
Thanks,
Matt
> [Reviewer: Andy] Astaire changes

- debian/bono.init.d
Graeme,
Please can you review this, which fixes #984?
Matt
> [Reviewer: Grame] Bono should use `cdf_identity` for CDF

- include/cfgoptions.h
- include/constants.h
- include/custom_headers.h
- include/pjutils.h
- include/scscfsproutlet.h
- include/sproutsasevent.h
- include/stack.h
- sprout/custom_headers.cpp
- sprout/main.cpp
- sprout/pjutils.cpp
- sprout/scscfsproutlet.cpp
- sprout/stack.cpp
- sprout/stateful_proxy.cpp
- sprout/ut/custom_headers_test.cpp
- sprout/ut/handlers_test.cpp
- sprout/ut/scscf_test.cpp
- sprout/ut/siptest.cpp
Andy, can you please review this change to support the Min-SE header. This fixes #529 (but doesn't fully support RFC 4028). 
Tested in UTs.
> [Reviewer: Andy] Support Min-SE header

- debian/control
Same fix as https://github.com/Metaswitch/homestead/pull/194.
> [No review required] Fix sprout-libs dependencies

- debian/bono.init.d
- debian/restund.init.d
- sprout-base.root/etc/init.d/sprout
Same as https://github.com/Metaswitch/homestead/pull/207.
> [Reviewer: Andy] Add service run command to run blocking

- sprout/icscfrouter.cpp
- sprout/ut/icscfsproutlet_test.cpp
Fixes https://github.com/Metaswitch/homestead/issues/210.
> [Reviewer: Ellie] ICSCF should send 480 when HSS sends 5003

- include/constants.h
Minor tweak to match https://github.com/Metaswitch/gemini/pull/21
> [Reviewer: Andy] Update g.3gpp.ics definition

- sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_chronos_plugin.py
Rob, can you review this change to add a chronos plugin to sprout
> [Reviewer: Rob] Add in Chronos plugin to Sprout

- bono.root/usr/share/clearwater/infrastructure/scripts/bono.monit
- restund.root/usr/share/clearwater/infrastructure/scripts/restund
- sprout-base.root/usr/share/clearwater/infrastructure/scripts/sprout.monit
Metaswitch/clearwater-monit#16
> [No reviewer] Add in groups

- sprout/handlers.cpp
Fix coverage failure caused by recent memcachedstore changes.
> [No reviewer] Exclude one line from coverage

- sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_json
As suggested, matching change to https://github.com/Metaswitch/clearwater-etcd/pull/59.
Matt
> [Reviewer: Andy] Default local_site_name

- sprout/registrar.cpp
- sprout/subscription.cpp
This adds the missing has_servers checks. 
Part of the fix for #1055
> [Reviewer: Matt] Add has servers checks

- sprout/main.cpp
Check whether I-CSCF or S-CSCF function is enabled when creating the enum_service
Fixes #1060
> [Reviewer: Matt] Add in check for I-CSCF

- sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_chronos_plugin.py
- sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_memcached_plugin.py
- sprout-base.root/usr/share/clearwater/clearwater-cluster-manager/plugins/sprout_remote_memcached_plugin.py
- sprout-base.root/usr/share/clearwater/clearwater-config-manager/plugins/sprout_bgcf_json_plugin.py
- sprout-base.root/usr/share/clearwater/clearwater-config-manager/plugins/sprout_enum_json_plugin.py
- sprout-base.root/usr/share/clearwater/clearwater-config-manager/plugins/sprout_scscf_json_plugin.py
Co-req change to accompany Metaswitch/clearwater-etcd#70
> [Reviewer: Andy] Etcd plugins now receive parameter objects

- sprout/enumservice.cpp
- sprout/ut/enumservice_test.cpp
- sprout/ut/fakednsresolver.cpp
- sprout/ut/fakednsresolver.hpp
Fixes #946. Tested in UT - I think that's enough and there's no need to test live.
> [Reviewer: Ellie] Don't alarm if someone dials an off-net number

- include/aschain.h
- sprout/aschain.cpp
Andy,
Please can you review the fix we just discussed to #1107?  I haven't finished running UT yet, but I will before I merge.
Thanks,
Matt
> [Reviewer: Andy] Make AsChain::inc_ref thread-safe

- sprout/thread_dispatcher.cpp
Alex,
Please can you review this partial fix to #587?  It doesn't go the whole way, but it should help in most cases.
Cheers,
Matt
> [Reviewer: Alex] Dump SAS trail (and related details) out when we hit an exception

- docs/Development.md
> [Reviewer: Ellie] Add SNMP AgentX information

- sprout/common_sip_processing.cpp
Tested live, by checking that every options poll triggered a SAS request beforehand:
```
09:11:22.647558 IP ec2-107-20-72-95.52812 > ec2-107-20-72-95.5054: Flags [.], ack 1, win 65, options [nop,nop,TS val 13959421 ecr 13959421], length 0
09:11:22.648370 IP ec2-107-20-72-95.52812 > ec2-107-20-72-95.5054: Flags [P.], seq 1:351, ack 1, win 65, options [nop,nop,TS val 13959421 ecr 13959421], length 350
09:11:22.648389 IP ec2-107-20-72-95.5054 > ec2-107-20-72-95.52812: Flags [.], ack 351, win 64, options [nop,nop,TS val 13959421 ecr 13959421], length 0
09:11:22.648573 IP ec2-107-20-72-95.52812 > ec2-107-20-72-95.5054: Flags [P.], seq 351:353, ack 1, win 65, options [nop,nop,TS val 13959421 ecr 13959421], length 2
09:11:22.648585 IP ec2-107-20-72-95.5054 > ec2-107-20-72-95.52812: Flags [.], …
```
> [Reviewer: Andy] Don't log the monit OPTIONS/200 OK polls to SAS

- sprout/authentication.cpp
> [Reviewer: Alex] Set the SAS trail on authentication responses

- sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_json
Matching fix to https://github.com/Metaswitch/clearwater-etcd/pull/153
> [Reviewer: Rob] Get output from upload_json

- sprout-base.root/usr/share/clearwater/infrastructure/alarms/sprout_alarms.json
This better? If you're happy with this, I'll make the equivalent change in Ralf too.
> Reviewer AMC: Edit Chronos connection alarm

- sprout/main.cpp
> [reviewer: Rob] Only delete registration stats tables if not running as bono

- sprout/authentication.cpp
- sprout/ut/authentication_test.cpp
> [reviewer: Rob] Fixed auth case where algorithm not specified in header

- clearwater-sip-stress.root/usr/share/clearwater/infrastructure/scripts/sip-stress
- restund.root/usr/share/clearwater/infrastructure/scripts/restund
Similar fix to https://github.com/Metaswitch/crest/pull/229
> [No reviewer] Check config before running scripts

- sprout/ut/basicproxy_test.cpp
Rob,
Please can you review my fix to strict-routed TEL URI support (fixes #1170)?  The main fix is in PJSIP, but this commit adds UT.
Matt
> [Reviewer: Rob] Fix strict-routed TEL URI support

- docs/Development.md
Add Bono to the development docs
> [Reviewer: Rob] Add Bono notes

- debian/bono.init.d
Add = in init.d to make it easier to debug missing parameters
Tested live
> [Reviewer: Rob] Use = in init.d

- clearwater-sip-stress.root/usr/share/clearwater/infrastructure/scripts/sip-stress
Set a more reasonable stress level
> [No reviewer] Change default stress level

- include/bgcfsproutlet.h
- include/custom_headers.h
- include/icscfsproutlet.h
- include/scscfsproutlet.h
- sprout/bgcfsproutlet.cpp
- sprout/custom_headers.cpp
- sprout/icscfsproutlet.cpp
- sprout/pjutils.cpp
- sprout/scscfsproutlet.cpp
- sprout/ut/sproutletproxy_test.cpp
> Compiler warnings

- sprout/stack.cpp
Fixes #1228.
Tested live.
Matt
> [Reviewer: Andy] Fix scribbler in additional home domains

- bono.root/usr/share/clearwater/node_type.d/20_bono
> [No reviewer] Add cluster key

- sprout/ut/load_monitor_test.cpp
UT for https://github.com/Metaswitch/cpp-common/pull/397. Also fixes up some unrealistic behaviour in UT, where we call `request_complete()` despite never having called `admit_request()`.
> [Reviewer: Alex] UT - don't increase our token rate spuriously during slow periods

- bono.root/usr/share/clearwater/infrastructure/scripts/bono.monit
- debian/bono.init.d
- include/cfgoptions.h
- sprout-base.root/etc/init.d/sprout
- sprout-base.root/usr/share/clearwater/infrastructure/scripts/sprout.monit
- sprout/main.cpp
Merging without review - this is basically identical to Metaswitch/chronos#191.
> [No reviewer] Implement a properly locked pidfile

- sprout/main.cpp
Markup to https://github.com/Metaswitch/sprout/pull/1258.
> [No reviewer] --pidfile takes an argument

- debian/bono.init.d
- sprout-base.root/etc/init.d/sprout
> [No reviewer] Create the pidfile directory even on 'make run'

- sprout-base.root/usr/share/clearwater/clearwater-config-manager/plugins/sprout_json_plugin.py
Part of https://github.com/Metaswitch/clearwater-etcd/pull/223.
> [No reviewer] Write files atomically, avoid corruption

- src/ut/load_monitor_test.cpp
I've occasionally seen the RequestComplete UT fail as it unexpectedly updates its rate. I think this is because the load monitor is created before time is controlled - this PR fixes this.
> [Reviewer: Rob] Fix up UT failure

- debian/control
Co-req change to https://github.com/Metaswitch/clearwater-net-snmp/pull/2.
> [No reviewer] Change version of SNMP libraries

- debian/bono.init.d
Rob,
Please can you review this, which fixes #1291?  (It was introduced by #1210.)
Tested live.
Matt
> [Reviewer: Rob] Correct namespace_prefix command

- src/main.cpp
- src/mementoasplugin.cpp
- src/ut/chronosconnection_test.cpp
- src/ut/communicationmonitor_test.cpp
- src/ut/enumservice_test.cpp
- src/ut/hssconnection_test.cpp
Corresponding changes to https://github.com/Metaswitch/cpp-common/pull/441. If these are OK, I'll make the same changes to the other repos
> [Reviewer: Andy] Use ENT logs in CM

- src/ut/communicationmonitor_test.cpp
Adds unit tests for the new communication monitor code in cpp-common. https://github.com/Metaswitch/cpp-common/pull/446
> [No Reviewer] Communication monitor UTs

- src/main.cpp
Related PR for https://github.com/Metaswitch/homestead/pull/295
> [Reviewer AMC] Default hss_reregistration_time based on reg_max_expires

- debian/memento-as.postinst
- debian/memento-as.triggers
- debian/sprout-base.postinst
- debian/sprout-base.triggers
Add alarm agent triggers - part of fix for https://github.com/Metaswitch/clearwater-snmp-handlers/issues/118
> [No reviewer] Add alarm triggers

- debian/bono.init.d
- debian/bono.prerm
- debian/sprout-base.prerm
- sprout-base.root/etc/init.d/sprout
> [No reviewer] Set PID ownership

- src/main.cpp
Just want to make sure this isn't going to break things. 
I've run UTs and they all still pass
> [Reviewer: Ellie] handle invalid session expires value better

- include/icscfrouter.h
- src/icscfrouter.cpp
- src/icscfsproutlet.cpp
> [Reviever: Andy] Only generate ACRs on Cx requests for INVITEs

- include/authentication.h
- include/cfgoptions.h
- include/handlers.h
- include/impistore.h
- include/registrar.h
- include/sproutsasevent.h
- sprout-base.root/etc/init.d/sprout
- src/authentication.cpp
- src/handlers.cpp
- src/main.cpp
- src/registrar.cpp
- src/ut/authentication_test.cpp
- src/ut/handlers_test.cpp
- src/ut/mock_impi_store.h
Hi Matt. My nonce count code is ready to be reviewed and merged into the main sto1119 branch. The current status is:
* I have written all the code and UTs I think I need to. 
* UTs are all passing
* Coverage in the authentication module and handlers 100%
* Valgrind is reporting some leaked authentication challenges but I think this is just because the version of the `ImpiStore` in my version of the code is incomplete. 
Thanks, Alex.
> [Reviewer: Matt] Code and UTs for non-store nonce-count support.

- src/authentication.cpp
- src/ut/authentication_test.cpp
Matt, please can you review my change to cope with data contention when creating auth challenges. Tested in UT.
> [Reviewer: Matt] Cope with data contention when creating a new challenge

- include/constants.h
- include/mangelwurzel/mangelwurzel.h
- include/sproutlet.h
- include/sproutletappserver.h
- src/cdivasplugin.cpp
- src/geminiasplugin.cpp
- src/mangelwurzel/mangelwurzelplugin.cpp
- src/mangelwurzel/ut/mangelwurzel_test.cpp
- src/mementoasplugin.cpp
- src/mmtelasplugin.cpp
- src/scscfsproutlet.cpp
- src/sproutletappserver.cpp
- src/sproutletproxy.cpp
- src/ut/scscf_test.cpp
Fix up how the app servers get their ports (so that they're the same as Sproutlets), and tidy up the code that matches URIs in sproutletproxy.
> [No reviewer] Fix up differences between sproutlets and app servers

- docs/Development.md
- include/cfgoptions.h
- sprout-base.root/etc/init.d/sprout
> [No reviewer] Change mmtel default

- debian/bono.init.d
- include/basicproxy.h
- include/cfgoptions.h
- include/stack.h
- sprout-base.root/etc/init.d/sprout
- src/basicproxy.cpp
- src/main.cpp
- src/sproutletproxy.cpp
- src/stack.cpp
Review was done under https://github.com/Metaswitch/sprout/pull/1376. This PR covers merging the code into a different branch.
> [No review required] Make sure the trying timer is not running when deleting a UASTsx

- debian/bono.init.d
- sprout-base.root/etc/init.d/sprout
- src/main.cpp
This is the sprout version of the fix for https://github.com/Metaswitch/cpp-common/issues/473 (cpp-common PR coming shortly) if you're happy I'll port to other C++ projects.
I'm testing live in parallel with your code review (as the changes are small but high risk :grinning:)
> Reviewer Rob - Daemonize ourselves when started by start-stop-daemon

- include/impistore.h
- src/impistore.cpp
- src/ut/impistore_test.cpp
Alex,
Please can you review this fix to #1394?  I've UT-ed and run clearwater-live-test against this.
I'm going to check with @JimBunch to confirm he wants this merged into release-94-fixes, but I think he will.
Thanks,
Matt
> [Reviewer: Alex] Fix (de)serialization of nonce_count and branch

- src/pjutils.cpp
Alex,
Please can you review my fix to #1407?  I'm just in the process of live-testing it, and will check with @JimBunch whether he wants it merged into release-94-fixes.
Thanks,
Matt
> [Reviewer: Alex] Don't free StatefulSendState too early

- src/main.cpp
Following the change in https://github.com/Metaswitch/cpp-common/pull/505
> [No reviewer] Use new signal handler start

- sprout-base.root/usr/share/clearwater/infrastructure/alarms/sprout_alarms.json
View the diff in split mode rather than unified mode (otherwise it's impossible to review). Sorry if that's totally obvious.
> Reviewer EM: Apply markups after evil Ellie's review comments

- src/ut/registrar_test.cpp
This splits up the registrar tests so that they don't share the fake hssconnection results. This stops the later tests being reliant on previous tests running first.
> [Reviewer: Adam] Make reg tests independent

- src/main.cpp
Uses https://github.com/Metaswitch/cpp-common/pull/511
> Use start from signal handlers

- include/hssconnection.h
- include/pjutils.h
- include/scscfsproutlet.h
- src/authentication.cpp
- src/hssconnection.cpp
- src/main.cpp
- src/pjutils.cpp
- src/registrar.cpp
- src/scscfsproutlet.cpp
- src/ut/authentication_test.cpp
- src/ut/fakehssconnection.cpp
- src/ut/handlers_test.cpp
- src/ut/hssconnection_test.cpp
- src/ut/mock_hss_connection.h
- src/ut/registrar_test.cpp
- src/ut/scscf_test.cpp
Fixes up the server name on SARs/MARs
> [Reviewer: Graeme] Fix server name mangling

- include/stack.h
Alex,
Please can you review this trivial fix to #1442?
Thanks,
Matt
> [Reviewer: Alex] Don't crash when CHECK_PJ_TRANSPORT_THREAD fails

- src/sipresolver.cpp
Corresponds to PRs https://github.com/Metaswitch/clearwater-sas-resources/pull/97 and https://github.com/Metaswitch/cpp-common/pull/515
> [Reviewer: Alex] Add SAS logging to the DNS Cached Resolver

- src/common_sip_processing.cpp
- src/ut/common_sip_processing_test.cpp
Updates given https://github.com/Metaswitch/cpp-common/pull/516
> [No reviewer] Updated load monitor function

- include/cfgoptions.h
- src/Makefile
- src/main.cpp
- src/mementoasplugin.cpp
- src/scscfplugin.cpp
- src/ut/as_communication_tracker_test.cpp
- src/ut/enumservice_test.cpp
- src/ut/hssconnection_test.cpp
Example of using the new AlarmManager in https://github.com/Metaswitch/cpp-common/pull/526
> [Reviewer: Rob] Use the new AlarmManager

- src/authentication.cpp
Error in PR https://github.com/Metaswitch/sprout/pull/1459
> misplaced coverage exception marker

- src/hss_sip_mapping.cpp
- src/ut/registrar_test.cpp
Missed out of https://github.com/Metaswitch/sprout/pull/1464
> [No review required] Map HSS responses to SIP failure codes coverage

- include/sproutlet.h
- src/sproutletproxy.cpp
Minor updates requested in the review of https://github.com/Metaswitch/sprout/pull/1480
> [No reviewer] Make minor fixes from review

- debian/bono.init.d
Andrew, this is mostly an FYI. I haven't written anything silly have I?
> [Reviewer: Andrew] Add a comment explaining why we clear the MIBS variable.

- src/bgcfplugin.cpp
- src/cdivasplugin.cpp
- src/geminiasplugin.cpp
- src/icscfplugin.cpp
- src/mementoasplugin.cpp
- src/mmtelasplugin.cpp
- src/pluginloader.cpp
- src/scscfplugin.cpp
More info in the commit messages.
> [Reviewer: Rob] Debuggable plugin disabled

- clearwater-sip-stress.root/etc/cron.hourly/clearwater-sip-stress-log-cleanup
Add a cleanup script for stress logs
> [No reviewer] Add stress log cleanup script

- src/pluginloader.cpp
Implements the log I suggested in https://github.com/Metaswitch/sprout/pull/1483#issuecomment-232662895
> [Reviewer: Chris] Report how many Sproutlets each plugin has created

- src/ut/authentication_test.cpp
Adds UT for #1404 to get 100% code coverage.  The test:
- Sends in a register.
- Forces the memcached SET to fail.
- Waits for 500 Server Internal Error.
cpp-common pull request to follow.
> [Reviewer: RKD] Add UT for memcached SET failure

- src/bgcfsproutlet.cpp
- src/ut/bgcf_test.cpp
Reviewed under https://github.com/Metaswitch/sprout/pull/1500
> [Reviewer: Ellie] Remove existing Route headers before the BGCF adds them

- src/basicproxy.cpp
This fixes #1531.  I've run UT but not repro-ed the exact scenario.  However, I really can't see how I'd have got this wrong.
> [Reviewer: Richard] Downgrade spurious TRC_ERROR to TRC_DEBUG

- src/common_sip_processing.cpp
- src/thread_dispatcher.cpp
- src/ut/common_sip_processing_test.cpp
> Don't generate response to ACK requests [reviewer RKD]

- include/cfgoptions.h
- src/main.cpp
- src/mementoasplugin.cpp
> [Reviewer RKD] Memento requires a CassandraResolver

- include/pjutils.h
- src/pjutils.cpp
Added method to extract parameter values from either TEL request URIs, or the userinfo section of SIP request URI's.
> [Reviewer: RKD] BGCF-23 PJUtils updates 

- src/main.cpp
- remove accidentally added extra if block that caused sprout to use a local
store if the deployment was not GR
> [No reviewer] Fix up previous merge

- src/ut/common_sip_processing_test.cpp
- src/ut/fakesnmp.cpp
- src/ut/fakesnmp.hpp
It looks like the Sprout UTs are failing, and this seems to fix it. Does this look sensible? If so, please merge. If not, feel free to fix it yourself. (I'm out for next few days).
> Reviewer SS5: Fix UTs

- debian/sprout-base.postinst
- sprout-base.root/etc/logrotate.d/sproutanalytics
This is the `nocreate` fix we discussed on Friday, and also the permissions commands in the postinst that I claimed I'd made but apparently hadn't actually done...
> Reviewer RJW2: Analytics logs fixes

- src/ut/hssconnection_test.cpp
- src/ut/xdmconnection_test.cpp
For metaswitch/cpp-common#582.
But don't merge this just yet!  memento-as also wants an update.  Please give me permission and I'll submit a pull there, and then update this one to include that.
> Pull latest cpp-common, for HTTPS support

- src/common_sip_processing.cpp
- src/pjutils.cpp
As discussed by email. I'll arrange some testing to see how much of a difference this makes.
> [Reviewer: Alex] Skip logging SAS markers if we can get away with it

- src/contact_filtering.cpp
just a random drive-by fix for you, because it seemed like the right thing to do
> Fix obvious typo in comparison of Targets

- src/impistore.cpp
Don't log an unhelpful return code
(part) fixes issue #1601 
the other part of the fix is in https://github.com/Metaswitch/cpp-common/pull/594
**testing**
- live tested
> [Reviewer: Ellie] SAS log improvements for memcached errors

- src/authentication.cpp
> [Reviewer: Matt] Make AKAv2 Auth thread safe

- docs/ManagementHttpAPI.md
This documents the API that was added by https://github.com/Metaswitch/sprout/pull/1559
> Reviewer ???: Add documentation for the management HTTP API

- src/basicproxy.cpp
Forgot coverage checks :turtle:
> [No reviewer] Exclude log from coverage

- debian/sprout-base.links
Companion PR to Metaswitch/clearwater-etcd#355
> [Reviewer EM] Add /usr/bin links to commonly used scripts

- src/authenticationsproutlet.cpp
> [Reviewer: EM] Change logging level to prevent spammy log

- include/sprout_pd_definitions.h
Live tested, fixed issue #1608
> ENT log changes for enum file wrong format.

- sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_json
#1757 Accidentally merged directly into dev, so merge into fix here.
> Fixed minor bugs for the check-upload-json-size commit Issue 1747.

- include/constants.h
- src/notify_utils.cpp
- src/ut/subscription_test.cpp
Add the ere namespace to the NOTIFY XML.
Tested in UTs.
> [Reviewer: Krista] Add the correct namespace to the XML

- src/basicproxy.cpp
- src/ut/basicproxy_test.cpp
Specifically, this one:
Error basicproxy.cpp:1798: Error sending CANCEL, Object already exists (PJ_EEXISTS)
this pull request includes a unit test case that hits this, and the simplest possible fix to avoid the unwarranted error log.
> A retransmitted CANCEL caused an Error log

- sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_json
This now handles an empty file, and we have better, more consistent error messages.
@steelyvoid , you wanted notifications about this work
> [Reviewer: Rob] Validate json files in the upload_json script, and log when they fail

- src/ut/registrar_test.cpp
Mat,
https://github.com/Metaswitch/sprout/pull/1635 introduced a bunch of console spam in the logs, as for all of the tests we monitor the HSS connection, however we only care about observing the HSS connection in the multiple registrations tests.
I've split RegistrarTest into two - one which observes the HSS Connection, and one which doesn't.
This also fixes up a bunch of duplicated code in RegistrarRemoteSDMTest.
> [Reviewer: Mat] Don't observe HSS connection in registrar tests

- src/ut/aschain_test.cpp
- src/ut/sifcservice_test.cpp
> [No reviewer] Use fakes for counter tables

- Makefile
Richard, please can you review this fix that makes the sprout build fail if one of the plugins fails to build. I've done this in a way that means plugin building plays nicely with `-k`.
Tested as follows:
* Clone `greeter` into the plugins directory and break it. 
* Run `make` from the top level. It exists with error code 2. 
* Run `make deb` from the top level. It exists with error code 2. 
* Clone another `greeter` into `greeter2`
* Run `make plugins-build`. This fails without building `greeter2`
* Run `make plugins-build -k`. This fails but builds `greeter2`
* Fix greeter. Run `make plugins-build`. This succeeds (exits with 0 error code)
> [Reviewer: Richard] Fail the sprout build if plugins fail to build. 

- debian/sprout-scscf.install
- debian/sprout-scscf.links
I've added the shortcut commands "cw-" for the two new scripts I added [here](https://github.com/Metaswitch/clearwater-etcd-plugins/pull/32).
> Add commands for new script

- src/mangelwurzel/mangelwurzel.cpp
Reverts Metaswitch/sprout#1860
> Revert "[Reviewer: Graeme] Save off original request for in-dialog transactions too"

- src/mangelwurzel/mangelwurzel.cpp
- src/mangelwurzel/ut/mangelwurzel_test.cpp
https://github.com/Metaswitch/sprout/pull/1860, done properly.
> Fix mangelwurzel crash on in-dialog requests

- include/aschain.h
- include/bono.h
- include/fifcservice.h
- include/ifc.h
- include/sifcservice.h
- include/sprout_pd_definitions.h
- src/aschain.cpp
- src/fifcservice.cpp
- src/hssconnection.cpp
- src/ifc.cpp
- src/ifchandler.cpp
- src/main.cpp
- src/scscfsproutlet.cpp
- src/sifcservice.cpp
- src/ut/aschain_test.cpp
- src/ut/fifcservice_test.cpp
- src/ut/hssconnection_test.cpp
- src/ut/registrar_test.cpp
- src/ut/scscf_test.cpp
- src/ut/sifcservice_test.cpp
This changes any instance of IFC -> iFC.
> [No reviewer] Use iFC consistently

- include/aschain.h
- include/handlers.h
- include/ifc.h
- include/ifchandler.h
- include/registrarsproutlet.h
- include/registration_utils.h
- src/aschain.cpp
- src/handlers.cpp
- src/ifchandler.cpp
- src/main.cpp
- src/registrarsproutlet.cpp
- src/registration_utils.cpp
- src/scscfplugin.cpp
- src/scscfsproutlet.cpp
- src/ut/aschain_test.cpp
- src/ut/handlers_test.cpp
- src/ut/ifchandler_test.cpp
- src/ut/registrar_test.cpp
- src/ut/scscf_test.cpp
- src/ut/test_registrar_fifc.xml
> [No reviewer] Misc IFC fixes

- sprout-base.root/usr/share/clearwater/clearwater-config-manager/scripts/config_validation/mmf_targets_schema.json
Jack,
Can you check this looks correct?
> [Reviewer: Jack Atack] Remove trailing comma in mmf_targets_schema

- include/pjutils.h
- include/registrarsproutlet.h
- include/scscf_utils.h
- include/sproutlet.h
- include/sproutletproxy.h
- src/authenticationsproutlet.cpp
- src/pjutils.cpp
- src/registrarsproutlet.cpp
- src/scscf_utils.cpp
- src/scscfsproutlet.cpp
- src/sproutletproxy.cpp
- src/ut/mocktsxhelper.h
As discussed, this modifies the way we build the S-CSCF URI slightly to swap out the local hostname part URI instead of building a new hostname.
> [Reviewer: AJH] Change how we build S-CSCF URI

- include/authenticationsproutlet.h
- include/hssconnection.h
- include/impistore.h
- include/registrarsproutlet.h
- include/scscf_utils.h
- include/scscfsproutlet.h
- include/sproutlet.h
- include/sproutletproxy.h
- include/subscriber_data_manager.h
- src/authenticationsproutlet.cpp
- src/forwardingsproutlet.cpp
- src/hssconnection.cpp
- src/main.cpp
- src/registrarsproutlet.cpp
- src/scscf_utils.cpp
- src/scscfsproutlet.cpp
- src/sproutletproxy.cpp
- src/subscriber_data_manager.cpp
- src/subscriptionsproutlet.cpp
- src/ut/fakehssconnection.cpp
- src/ut/fakehssconnection.hpp
- src/ut/handlers_test.cpp
- src/ut/hssconnection_test.cpp
- src/ut/mock_hss_connection.h
- src/ut/mocktsxhelper.h
- src/ut/registrar_test.cpp
- src/ut/scscf_test.cpp
- src/ut/sproutletproxy_test.cpp
> [No Reviewer] Markups from S-CSCF URI fix

- src/ut/subscription_test.cpp
Add missing UTs resulting from https://github.com/Metaswitch/sprout/pull/1800 to fix coverage issues
> [No reviewer] Resolve coverage issue on SUBSCRIBEs

- include/authenticationsproutlet.h
- include/cfgoptions.h
- include/impistore.h
- include/subscriber_data_manager.h
- sprout-base.root/etc/init.d/sprout
- src/authenticationsproutlet.cpp
- src/handlers.cpp
- src/impistore.cpp
- src/main.cpp
- src/registrarsproutlet.cpp
- src/subscriber_data_manager.cpp
- src/ut/authentication_test.cpp
- src/ut/bono_test.cpp
- src/ut/contact_filtering_test.cpp
- src/ut/gruu_test.cpp
- src/ut/handlers_test.cpp
- src/ut/ifchandler_test.cpp
- src/ut/impistore_test.cpp
- src/ut/mock_impi_store.h
- src/ut/mock_subscriber_data_manager.cpp
- src/ut/registrar_test.cpp
- src/ut/scscf_test.cpp
- src/ut/subscriber_data_manager_test.cpp
- src/ut/subscription_test.cpp
This PR:
- Deletes the binary serializer/deserializer from the subscriber data manger.
- Deletes the AV store from the impi store.
> [Reviewer: EM] Remove dead code

- src/bgcfservice.cpp
- src/enumservice.cpp
- src/handlers.cpp
- src/pjutils.cpp
- src/uri_classifier.cpp
[Reviewer AJH] Changes to sprout in light of some pjutils function being refactored into cpp-common
Companion PR to https://github.com/Metaswitch/homestead/pull/470
> Allow RTRs to be searchable in SAS

- src/scscfsproutlet.cpp
Tested by running `make full_test`
> Delete AOR binding

- src/hssconnection.cpp
Long term these should be SAS logs, but we need these for now.
> [No reviewer] Add more detail to WARNING logs

- src/acr.cpp
- src/ut/acr_asregister.json
- src/ut/acr_bgcforigcall_start.json
- src/ut/acr_ibcforigcall_start.json
- src/ut/acr_ibcftermcall_start.json
- src/ut/acr_icscfregister_caps.json
- src/ut/acr_icscfregister_final.json
- src/ut/acr_pcscfregister.json
- src/ut/acr_scscfcancel.json
- src/ut/acr_scscfnotify.json
- src/ut/acr_scscforigcall_interim.json
- src/ut/acr_scscforigcall_stop.json
- src/ut/acr_scscfregister.json
- src/ut/acr_scscfsubscribe.json
- src/ut/acr_test.cpp
- src/ut/mock_ralf_processor.h
- src/ut/scscf_test.cpp
Increased the coverage from 85% to 100%. The code is kind of messy, submit for any functional feedback.
TODO:
1. Improve get_max_expiry function
2. Complete_control_time to fix timestamp
3. Fix all expected json.
Commented out for future:
1. Test real flow without CCF
2. If many fields like expiry, method, and SDP should be stored on all request rather than just the first request in a dialog
> [Reviewer: Ellie] ACR Coverage

- include/notify_utils.h
- include/registration_utils.h
- include/subscriber_data_manager.h
- src/handlers.cpp
- src/notify_utils.cpp
- src/registrarsproutlet.cpp
- src/registration_utils.cpp
- src/scscfsproutlet.cpp
- src/subscriber_data_manager.cpp
- src/subscriptionsproutlet.cpp
- src/ut/chronoshandlers_test.cpp
- src/ut/handlers_test.cpp
- src/ut/mock_subscriber_data_manager.h
- src/ut/registrar_test.cpp
- src/ut/scscf_test.cpp
- src/ut/siptest.cpp
- src/ut/subscriber_data_manager_test.cpp
- src/ut/subscription_test.cpp
Reverts Metaswitch/sprout#1944
> Revert "Notify on deregister"

- include/notify_utils.h
- include/registration_utils.h
- include/subscriber_data_manager.h
- src/handlers.cpp
- src/notify_utils.cpp
- src/registrarsproutlet.cpp
- src/registration_utils.cpp
- src/scscfsproutlet.cpp
- src/subscriber_data_manager.cpp
- src/subscriptionsproutlet.cpp
- src/ut/chronoshandlers_test.cpp
- src/ut/handlers_test.cpp
- src/ut/mock_subscriber_data_manager.h
- src/ut/registrar_test.cpp
- src/ut/scscf_test.cpp
- src/ut/siptest.cpp
- src/ut/subscriber_data_manager_test.cpp
- src/ut/subscription_test.cpp
Reverts Metaswitch/sprout#1975
> Revert "Revert "Notify on deregister""

- src/notify_utils.cpp
- src/subscriber_data_manager.cpp
- src/ut/subscription_test.cpp
TODO for test exclusion, will cover that later. Request to merge this branch of fix the build. 
`make full_test` passed.
> Fix build failure by adding default for switch

- include/cfgoptions.h
- sprout-base.root/etc/init.d/sprout
- src/main.cpp
- src/mementoasplugin.cpp
- src/ut/common_sip_processing_test.cpp
This plumbs through a config option for the max token rate to the load monitor.
I've also made the various load monitor options specific to the process type.
Tested in UTs only,
I've got the same change in all the repos - I won't send these to you for review.
> [Reviewer: Krista] Add max rate

- debian/sprout-bgcf.install
> Removes no longer existing .install file

- src/ut/handlers_test.cpp
- src/ut/handlers_test.h
- src/ut/registrar_test.cpp
- src/ut/scscf_test.cpp
To remove any NiceMock that I added. `make full_test` passed.
> Remove nice mock

- src/thread_dispatcher.cpp
- src/ut/thread_dispatcher_test.cpp
Contains the markups for https://github.com/Metaswitch/sprout/pull/2006
> Markups for https://github.com/Metaswitch/sprout/pull/2006

- src/handlers.cpp
- src/ifc.cpp
- src/scscfselector.cpp
- src/stack.cpp
- src/ut/as_communication_tracker_test.cpp
- src/ut/chronoshandlers_test.cpp
- src/ut/handlers_test.cpp
- src/ut/subscriber_data_manager_test.cpp
Fixes up the various uninteresting calls in the UTs
> [Reviewer: Krista] Fix up uninteresting calls

- include/impistore.h
- src/authenticationsproutlet.cpp
- src/impistore.cpp
- src/ut/authentication_test.cpp
This (along with https://github.com/Metaswitch/cpp-common/pull/717 and https://github.com/Metaswitch/sas-client/pull/78) fixes https://github.com/Metaswitch/clearwater-issues/issues/2730 and https://github.com/Metaswitch/clearwater-issues/issues/2505 and (probably) https://github.com/Metaswitch/clearwater-issues/issues/2602
See discussion of fix in https://github.com/Metaswitch/clearwater-issues/issues/2505.
UTs have been enhanced to cover this fix, and it has also been tested live.
> Fix register correlation

- sprout-base.root/etc/init.d/sprout
max_tokens should be process specific.
> [No reviewer] Fix up wrong param

- src/main.cpp
- src/thread_dispatcher.cpp
- src/ut/thread_dispatcher_test.cpp
Sprout changes to use https://github.com/Metaswitch/cpp-common/pull/724. I've also updated the sprout default token options.
> [Reviewer: Sathiyan] Updates to admit requests

- src/main.cpp
- src/stack.cpp
Ellie, these are the co-req sprout changes for https://github.com/Metaswitch/cpp-common/pull/721. Please can you review and, if you;re happy, I will apply these to the rest of the codebase.
> Log basic stack trace unless aborting

- sprout-base.root/usr/share/clearwater/bin/poll_sprout_http.sh
- sprout-base.root/usr/share/clearwater/bin/poll_sprout_sip.sh
- sprout-base.root/usr/share/clearwater/infrastructure/monit_stability/sprout-stability
- sprout-base.root/usr/share/clearwater/infrastructure/scripts/sprout.monit
Process-specific changes for [#522](https://github.com/Metaswitch/clearwater-infrastructure/pull/522).
> [Reviewer: EM] Improve Monit polling behavior during monitored process restart

- .gitmodules
Required for https://github.com/Metaswitch/curl/pull/2
> [No reviewer] Move to using a fork of CURL

- src/thread_dispatcher.cpp
- src/ut/thread_dispatcher_test.cpp
Reverts some of the changes in #2032 to get latency working.
> [Reviewer: RJW2] Revert change to admit all requests

- sprout-base.root/etc/init.d/sprout
- src/main.cpp
- src/scscfsproutlet.cpp
- src/thread_dispatcher.cpp
- src/ut/thread_dispatcher_test.cpp
Revert https://github.com/Metaswitch/sprout/pull/2037/files
> [No reviewer] Add back token cost

- src/authenticationsproutlet.cpp
- src/basicproxy.cpp
- src/contact_filtering.cpp
- src/rphservice.cpp
- src/scscfsproutlet.cpp
- src/sip_connection_pool.cpp
- src/websockets.cpp
Fixes to static analysis warnings and some general tidy up
> [Reviewer: Krista] Fix up static analysis warnings

- src/ut/chronoshandlers_test.cpp
> Memory leak

- include/handlers.h
- include/subscriber_manager.h
- src/Makefile
- src/handlers.cpp
- src/main.cpp
- src/ut/handlers_test.cpp
- src/ut/handlers_test.h
- src/ut/mock_subscriber_manager.cpp
- src/ut/mock_subscriber_manager.h
1. Add header for SubscriberManager and its Mock
2. Change the PPR and make the UT pass
Merge without review so that the header file can be shared. Any markups will affect the PPR Task alone.
> PPR Task uses SM

- include/subscriber_manager.h
- src/ut/mock_subscriber_manager.h
@eleanor-merry I think we've already discussed these changes so I'm going to go ahead and merge. Let me know if you have any comments and I'll apply them in a separate PR.
> [Reviewer: EM] Update SM management API

- include/subscriber_manager.h
- src/ut/mock_subscriber_manager.h
- Marked functions as virtual and mocked them out.
- Deleted SubscriberInfo object.
> More SM management API changes

- include/scscfsproutlet.h
- src/main.cpp
- src/scscfsproutlet.cpp
- src/ut/scscf_test.cpp
- src/ut/siptest.cpp
- src/ut/siptest.hpp
In total this work:
-small fixes following on from refactor in PR #2069 
-fixes up the tests
It's worth reviewing each commit separately, as I give the methods I used to get the tests to pass
> Small fixes, and getting scscf tests to pass

- src/scscfsproutlet.cpp
- src/ut/scscf_test.cpp
Follow on from #2087 and #2069
> More test fixes

- src/ut/scscf_test.cpp
Continues from PRs #2088, #2087, #2069, #2096 and #2098.
> More scscf ut fixes

- src/ut/aor_test_utils.h
- src/ut/s4_test.cpp
> Chronos Timer UT

- include/hssconnection.h
- src/scscfsproutlet.cpp
- src/ut/mock_subscriber_manager.h
- src/ut/overall_test_cases_to_add.cpp
- src/ut/scscf_test.cpp
Continues from PRs #2088, #2087, #2069, #2096, #2098 and #2101.
> More scscf test changes

- src/scscfsproutlet.cpp
- src/ut/scscf_test.cpp
Follow on from #2088, #2087, #2069, #2096, #2098, #2101, #2108, #2116, #2123 and #2129.
> Finish off scscf sproutlet work

- include/scscfsproutlet.h
- src/contact_filtering.cpp
- src/scscfsproutlet.cpp
- src/ut/mock_subscriber_manager.h
- src/ut/scscf_test.cpp
- src/ut/siptest.cpp
Follow on from #2088, #2087, #2069, #2096, #2098, #2101, #2108, #2116, #2123, #2129 and #2133.
> scscf work for sdm refactor

- include/scscfsproutlet.h
- src/scscfsproutlet.cpp
- src/ut/scscf_test.cpp
Follow on from:
#2088 
#2087 
#2069  
#2096  
#2098  
#2101  
#2108 
#2116 
#2123 
#2129 
#2133 
#2139
> More changes to S-CSCF sproutlet for SDM refactor.

- src/ut/notify_sender_test.cpp
- src/ut/scscf_test.cpp
> subscriber_data_utils coverage

- src/aor_utils.cpp
- src/contact_filtering.cpp
- src/handlers.cpp
- src/registrarsproutlet.cpp
- src/sprout_xml_utils.cpp
- src/ut/contact_filtering_test.cpp
- src/ut/hssconnection_test.cpp
- src/ut/registrar_test.cpp
- src/ut/s4_test.cpp
- src/ut/sprout_xml_utils_test.cpp
This PR tidies up the code a bit, fixes up the behaviour if you use the wildcard contact header, and improves the general UT coverage.
> [Reviewer: Graeme] Coverage fixes

- include/scscfsproutlet.h
- src/scscfsproutlet.cpp
- src/sprout_xml_utils.cpp
- src/ut/scscf_test.cpp
We talked about aliases last week, and you mentioned that we should add a TODO to the code.
Is this the sort of thing you were looking for?
The only file which needs reviewing is src/sprout_xml_utils.cpp (I'm just storing the rest of my stuff here so I don't lose it).
> Add comment about aliases to code

- src/ut/s4_test.cpp
The UTs create the AOR_BINDING string at compile time, giving the AoR 500 seconds before it expired. If it took more than 500 seconds to get to the UTs that used this string though then the AoR was expired, and the handle_timer_pop functions were called.
This PR creates the AOR_BINDING string as necessary.
> [Reviewer: Sathiyan] Fix UT crash

- src/ut/authentication_test.cpp
Reviewed by JA4 over shoulder.
> Fix marker typo

- src/Makefile
- src/main.cpp
See https://github.com/Metaswitch/sprout/pull/2099
> Load records from /etc/clearwater/dns.json

- include/pjutils.h
- include/registrarsproutlet.h
- src/pjutils.cpp
- src/registrarsproutlet.cpp
- src/ut/aor_test_utils.h
- src/ut/registrar_test.cpp
- src/ut/scscf_test.cpp
Merge https://github.com/Metaswitch/sprout/pull/2095/files given the SDM rework
> [No reviewer] Merge path header

- src/sproutletproxy.cpp
> [Reviewer: Tom] Send the remote alias SAS log
